# Generated by Django 6.0.5 on 2026-07-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_generations',
            field=models.IntegerField(default=5),
        ),
    ]
