# Generated by Django 6.0.5 on 2026-07-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_allowed_generations'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(default='Standard', max_length=20),
        ),
    ]
