# Generated by Django on 2026-10-05

from django.db import migrations

def backfill_study_time(apps, schema_editor):
    User = apps.get_model('authentication', 'User')
    CourseProgress = apps.get_model('syllabus', 'CourseProgress')
    UserAttempt = apps.get_model('exams', 'UserAttempt')

    for user in User.objects.all():
        completed_courses = CourseProgress.objects.filter(user=user, is_completed=True).count()
        total_attempts = UserAttempt.objects.filter(user=user).count()
        est_seconds = int(((completed_courses * 20) + (total_attempts * 1.5)) * 60)
        
        current_seconds = user.total_study_seconds or 0
        if current_seconds < est_seconds:
            user.total_study_seconds = est_seconds
            user.save(update_fields=['total_study_seconds'])

def reverse_backfill(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_is_archived'),
    ]

    operations = [
        migrations.RunPython(backfill_study_time, reverse_code=reverse_backfill),
    ]
