# Generated by Django 6.0.5 on 2026-07-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examsession_options_and_more'),
        ('syllabus', '0002_course_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='syllabus.course'),
        ),
    ]
