# Generated by Django 6.0.5 on 2026-09-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reference_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
