# Generated by Django on 2026-10-05

from django.db import migrations

def update_q21(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')
    
    new_question_text = (
        "On considère le programme Java suivant :\n"
        "```java\n"
        "class A {\n"
        "    private int x = 5;\n"
        "    public int getX() { return x; }\n"
        "}\n"
        "class B extends A { }\n"
        "\n"
        "class C {\n"
        "    private A a;\n"
        "    public C(A a) { this.a = a; }\n"
        "}\n"
        "class D {\n"
        "    private C c = new C(new A());\n"
        "}\n"
        "```\n"
        "Quelle relation correspond à la déclaration de C dans la classe D ?"
    )

    new_explanation = (
        "Dans la classe `D`, l'attribut `c` est déclaré et instancié directement à la déclaration :\n"
        "```java\n"
        "class D {\n"
        "    private C c = new C(new A());\n"
        "}\n"
        "```\n\n"
        "- **Composition (réponse D)** : C'est une relation d'appartenance forte (« a-un » / *has-a* ou *part-whole*). "
        "La classe `D` crée elle-même l'instance de `C` et en contrôle le cycle de vie : l'objet `c` n'existe pas indépendamment de `D`. "
        "Si l'instance de `D` est détruite, son instance `c` disparaît avec lui.\n"
        "- **Différence avec l'Agrégation (C)** : Dans la classe `C`, le constructeur `public C(A a) { this.a = a; }` reçoit une référence d'un objet `A` déjà existant à l'extérieur. C'est de l'agrégation car `a` peut continuer à exister indépendamment de `C`.\n"
        "- **Différence avec l'Héritage (A)** : `class B extends A` illustre l'héritage (« est-un » / *is-a*), ce qui n'est pas le cas pour `C` dans `D`.\n\n"
        "La bonne réponse est donc **D (Composition)**."
    )

    new_astuce = (
        "Astuce pour les concours :\n"
        "- Si l'objet interne est créé avec `new` directement à l'intérieur de la classe conteneur (durée de vie liée), c'est une **Composition** (lien fort).\n"
        "- Si l'objet provient de l'extérieur (ex: passé au constructeur ou setter), c'est une **Agrégation** (lien faible).\n"
        "- Le mot-clé `extends` correspond à l'**Héritage**."
    )

    new_option_e = "Aucune de ces réponses n'est juste"

    Question.objects.filter(question_number='Q21', exam_year=2025).update(
        question_text=new_question_text,
        option_e=new_option_e,
        explanation=new_explanation,
        astuce=new_astuce,
        correct_option='D'
    )

def reverse_q21(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_question_reference_text'),
    ]

    operations = [
        migrations.RunPython(update_q21, reverse_code=reverse_q21),
    ]
