# Generated by Django on 2026-10-05

from django.db import migrations

def update_questions(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')

    q23_text = (
        "On considère le programme Java suivant :\n"
        "```java\n"
        "public class Main {\n"
        "    public static void main(String[] args) {\n"
        "        int[] tab = { 1, 2, 3, 4 };\n"
        "        int somme = 0;\n"
        "        for (int i = 0; i <= tab.length; i++) {\n"
        "            somme += tab[i];\n"
        "        }\n"
        "        System.out.println(\"Somme : \" + somme);\n"
        "    }\n"
        "}\n"
        "```\n"
        "Que va afficher ce programme ?"
    )

    q23_explanation = (
        "Le tableau `tab` est initialisé avec 4 éléments : `{1, 2, 3, 4}`.\n"
        "- La propriété `tab.length` vaut donc **4**.\n"
        "- Les indices valides d'un tableau Java de taille 4 vont de **0 à 3** (`tab[0]`, `tab[1]`, `tab[2]`, `tab[3]`).\n\n"
        "Dans la boucle :\n"
        "```java\n"
        "for (int i = 0; i <= tab.length; i++) {\n"
        "    somme += tab[i];\n"
        "}\n"
        "```\n"
        "Remarquez l'opérateur **`<=`** au lieu de `<` :\n"
        "- Lorsque `i` atteint la valeur **4**, la condition `4 <= 4` est encore **vraie**.\n"
        "- Le programme tente alors d'exécuter `somme += tab[4]`.\n"
        "- L'indice `4` étant hors limites, la machine virtuelle Java (JVM) lève immédiatement une exception **`java.lang.ArrayIndexOutOfBoundsException`** à l'exécution.\n\n"
        "Le programme s'interrompt donc avec une erreur avant d'afficher la somme.\n\n"
        "La bonne réponse est donc **D (Le programme affichera une erreur d'exécution)**."
    )

    q23_astuce = (
        "Astuce Concours :\n"
        "- Toujours vérifier l'opérateur de comparaison dans les boucles de parcours de tableau :\n"
        "  - **`i < tab.length`** est la forme correcte (indices de `0` à `N - 1`).\n"
        "  - **`i <= tab.length`** tente d'accéder à l'indice `N`, provoquant inévitablement une erreur d'exécution `ArrayIndexOutOfBoundsException`."
    )

    q24_text = (
        "On considère le code PHP suivant :\n"
        "```php\n"
        "<?php\n"
        "$x = null;\n"
        "$y = 0;\n"
        "$z = '';\n"
        "echo $x ?? $y ?? $z ?? 'aucun';\n"
        "echo PHP_EOL;\n"
        "?>\n"
        "```\n"
        "Qu'affiche ce script PHP ?"
    )

    q25_text = (
        "On propose le code JavaScript suivant :\n"
        "```javascript\n"
        "let x = 5;\n"
        "function test() {\n"
        "    console.log(x);\n"
        "    let x = 10;\n"
        "}\n"
        "test();\n"
        "```\n"
        "Que va afficher ce script JavaScript ?"
    )

    Question.objects.filter(question_number='Q23', exam_year=2025).update(
        question_text=q23_text,
        explanation=q23_explanation,
        astuce=q23_astuce
    )

    Question.objects.filter(question_number='Q24', exam_year=2025).update(
        question_text=q24_text
    )

    Question.objects.filter(question_number='Q25', exam_year=2025).update(
        question_text=q25_text
    )

def reverse_update(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_update_q21_2025'),
    ]

    operations = [
        migrations.RunPython(update_questions, reverse_code=reverse_update),
    ]
