# Generated by Django on 2026-10-05

from django.db import migrations

def update_q27(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')

    q27_text = (
        "Quelle sera la sortie de ce code ?\n"
        "```php\n"
        "<?php\n"
        "for ($x = 1; $x <= 3; $x++) {\n"
        "    if ($x == 2) {\n"
        "        continue;\n"
        "    }\n"
        "    echo $x;\n"
        "}\n"
        "?>\n"
        "```"
    )

    q27_explanation = (
        "Détaillons pas à pas l'exécution de la boucle `for` en PHP :\n\n"
        "- **1ère itération (`$x = 1`)** :\n"
        "  - La condition `$x <= 3` (1 <= 3) est **vraie**.\n"
        "  - Le test `if ($x == 2)` est **faux** (1 != 2).\n"
        "  - L'instruction `echo $x;` est exécutée et affiche **`1`**.\n"
        "  - Incrémentation : `$x++` fait passer `$x` à **2**.\n\n"
        "- **2ème itération (`$x = 2`)** :\n"
        "  - La condition `$x <= 3` (2 <= 3) est **vraie**.\n"
        "  - Le test `if ($x == 2)` est **vrai** (2 == 2).\n"
        "  - L'instruction **`continue;`** est immédiatement exécutée : elle interrompt l'itération en cours et saute directement à l'incrémentation suivante, en **ignorant** l'instruction `echo $x;`. Le chiffre **2 n'est donc pas affiché**.\n"
        "  - Incrémentation : `$x++` fait passer `$x` à **3**.\n\n"
        "- **3ème itération (`$x = 3`)** :\n"
        "  - La condition `$x <= 3` (3 <= 3) est **vraie**.\n"
        "  - Le test `if ($x == 2)` est **faux** (3 != 2).\n"
        "  - L'instruction `echo $x;` est exécutée et affiche **`3`**.\n"
        "  - Incrémentation : `$x++` fait passer `$x` à **4**.\n\n"
        "- **Sortie de boucle (`$x = 4`)** :\n"
        "  - La condition `$x <= 3` (4 <= 3) est **fausse**, la boucle se termine.\n\n"
        "Le résultat final affiché à l'écran est donc la suite des valeurs affichées : **`13`** (Option **C**)."
    )

    q27_astuce = (
        "💡 **Différence essentielle en PHP / Algorithmique** :\n"
        "- **`continue`** : saute la fin de l'itération en cours et passe directement à l'itération suivante. Ici, il permet de sauter l'affichage de `$x` uniquement pour `$x == 2`.\n"
        "- **`break`** : interrompt définitivement et sort immédiatement de la boucle. Si le code avait utilisé `break`, la boucle se serait arrêtée dès `$x == 2` et la sortie aurait été `1`."
    )

    Question.objects.filter(question_number='Q27', exam_year=2025, domain_id='DEV').update(
        question_text=q27_text,
        option_a="123",
        option_b="12",
        option_c="13",
        option_d="23",
        option_e="Aucune de ces réponses n'est juste",
        correct_option="C",
        explanation=q27_explanation,
        astuce=q27_astuce
    )

def reverse_update(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_format_q23_q25_2025'),
    ]

    operations = [
        migrations.RunPython(update_q27, reverse_code=reverse_update),
    ]
