# Generated by Django on 2026-10-08

from django.db import migrations

def fix_2024_questions(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')
    
    # 1. Restore Q17, Q18, Q19, Q20 to LOG / LOG_OFFICE
    Question.objects.filter(pk=221).update(domain_id='LOG', subdomain_id='LOG_OFFICE')
    Question.objects.filter(pk=222).update(domain_id='LOG', subdomain_id='LOG_OFFICE')
    Question.objects.filter(pk=223).update(domain_id='LOG', subdomain_id='LOG_OFFICE')
    Question.objects.filter(pk=224).update(domain_id='LOG', subdomain_id='LOG_OFFICE')
    
    # 2. Restore Q44, Q46 to DEV / DEV_SI_BD
    Question.objects.filter(pk=248).update(domain_id='DEV', subdomain_id='DEV_SI_BD')
    Question.objects.filter(pk=250).update(domain_id='DEV', subdomain_id='DEV_SI_BD')
    
    # 3. Ensure didactique Q21, Q22 have domain DIDACTIQUE
    Question.objects.filter(pk=1213).update(domain_id='DIDACTIQUE', subdomain_id='DID_CONCEPTS')
    Question.objects.filter(pk=1214).update(domain_id='DIDACTIQUE', subdomain_id='DID_CONCEPTS')

def reverse_fix(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_fix_q27_2025'),
    ]

    operations = [
        migrations.RunPython(fix_2024_questions, reverse_code=reverse_fix),
    ]
