# Generated by Django on 2026-10-09

from django.db import migrations

def fix_q4_2024(apps, schema_editor):
    Question = apps.get_model('exams', 'Question')
    
    explanation_text = (
        "Dans Microsoft Word, il existe 4 types de sauts de section :\n\n"
        "- **Page suivante** → commence la nouvelle section sur une nouvelle page.\n"
        "- **Continu** → commence la nouvelle section sur la même page.\n"
        "- **Page paire** → commence la section sur la prochaine page paire.\n"
        "- **Page impaire** → commence la section sur la prochaine page impaire."
    )
    
    astuce_text = (
        "🧠 **Astuce concours**\n\n"
        "Saut de section = 4 types :\n"
        "**Page suivante – Continu – Page paire – Page impaire**"
    )
    
    Question.objects.filter(pk=208).update(
        correct_option='C',
        explanation=explanation_text,
        astuce=astuce_text
    )

def reverse_fix(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_restore_2024_exam_questions'),
    ]

    operations = [
        migrations.RunPython(fix_q4_2024, reverse_code=reverse_fix),
    ]
