# Generated by Django 6.0.5 on 2026-07-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.CharField(blank=True, help_text='Lien de la vidéo YouTube de la leçon', max_length=500, null=True),
        ),
    ]
