# Generated by Django 6.0.5 on 2026-08-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0002_course_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_ar',
            field=models.TextField(blank=True, help_text='Contenu en arabe (cours bilingues)', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='content_fr',
            field=models.TextField(blank=True, help_text='Contenu en français (cours bilingues)', null=True),
        ),
    ]
