# Generated by Django 6.0.5 on 2026-09-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0003_course_content_ar_course_content_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='astuces_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='astuces_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='examples_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='examples_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
