# Generated by Django on 2026-10-05

from django.db import migrations, models

POO_CONTENT = """# Programmation Orientée Objet (POO) : Java et C++

## 1. Introduction à la POO
La **Programmation Orientée Objet (POO)** est un paradigme de programmation basé sur la création de « composants logiciels autonomes » appelés **objets**, qui combinent à la fois des **données** (attributs / état) et des **traitements** (méthodes / comportement).

---

## 2. Les 4 Piliers Fondamentaux de la POO

### A. L'Encapsulation (Protection des données)
* **Principe** : Masquer l'état interne d'un objet et interdire son accès direct depuis l'extérieur afin de garantir l'intégrité et la cohérence des données.
* **Mise en œuvre** :
  * Attributs déclarés `private` ou `protected`.
  * Accès contrôlé via des méthodes publiques (**Getters** pour lire, **Setters** pour valider et modifier).
* **Avantages** : Robustesse, découplage et facilité de maintenance.

```java
// Exemple d'Encapsulation en Java
public class CompteBancaire {
    private double solde; // Attribut privé, inaccessible directement

    public double getSolde() {
        return this.solde;
    }

    public void deposer(double montant) {
        if (montant > 0) {
            this.solde += montant;
        }
    }
}
```

---

### B. L'Héritage (Spécialisation et Réutilisation — Relation « Est-Un » / Is-A)
* **Principe** : Définir une nouvelle classe (**classe fille / dérivée**) à partir d'une classe existante (**classe mère / de base**). La classe fille hérite des attributs et méthodes non privés de la classe mère.
* **Mots-clés** :
  * **Java** : `extends` (Héritage simple unique pour les classes).
  * **C++** : `: public BaseClass` (Héritage multiple autorisé entre classes).
* **Principe de substitution de Liskov (LSP)** : Partout où un objet de la classe de base est attendu, une instance de la classe dérivée doit pouvoir être utilisée sans altérer le fonctionnement du programme.

---

### C. Le Polymorphisme (Flexibilité d'exécution)
Le polymorphisme permet à une même méthode d'avoir des comportements différents selon l'objet qui l'exécute.

1. **Polymorphisme Statique (Surcharge / Overloading)** :
   * Plusieurs méthodes portant le **même nom** dans la **même classe**, mais avec des **signatures différentes** (nombre ou types de paramètres distincts).
   * Résolu à la **compilation** (*Early Binding / Liaison précoce*).

2. **Polymorphisme Dynamique (Redéfinition / Overriding)** :
   * La classe fille fournit sa propre implémentation d'une méthode de la classe mère (annotation `@Override` en Java, mot-clé `virtual` en C++).
   * Résolu à **l'exécution** via le mécanisme de liaison tardive (**Dynamic Binding / Late Binding**).

---

### D. L'Abstraction (Contrats et Modélisation)
* **Principe** : Exprimer ce qu'un composant doit faire sans en imposer la réalisation technique.
* **Classe Abstraite (`abstract class`)** :
  * Ne peut **jamais être instanciée** directement (`new ClasseAbstraite()` génère une erreur de compilation).
  * Peut contenir à la fois des méthodes abstraites (sans corps) et des méthodes concrètes (avec corps).
* **Interface (`interface`)** :
  * Contrat pur contenant uniquement des signatures de méthodes (et des constantes `public static final`).
  * En Java, une classe peut implémenter **plusieurs interfaces** (`implements A, B`), ce qui compense l'absence d'héritage multiple.

---

## 3. Les Relations entre Classes en POO (Focus Concours CRMEF)

En modélisation et programmation orientée objet, l'héritage n'est pas la seule relation possible. Les épreuves de concours testent très fréquemment la distinction fondamentale entre **Association**, **Agrégation** et **Composition**.

```
             ┌─────────────────────────┐
             │  Relations entre Objets │
             └────────────┬────────────┘
        ┌─────────────────┼─────────────────┐
        ▼                 ▼                 ▼
   Héritage          Association       Dépendance
  (« Est-un »)      (« Connaît-un »)  (« Utilise-un »)
                          │
            ┌─────────────┴─────────────┐
            ▼                           ▼
        Agrégation                 Composition
      (Lien faible ◇)            (Lien fort ◆)
```

### 1. L'Association (« Connaît-un » / Uses-A)
* **Définition** : Relation structurelle entre deux classes indépendantes. Un objet collabore avec un autre sans posséder son cycle de vie.
* **Exemple** : Un `Enseignant` donne un cours dans une `Salle`. L'enseignant utilise la salle, mais ils existent séparément.
* **UML** : Trait simple reliant les deux classes (`───────`).

---

### 2. L'Agrégation (« A-un » Faible / Shared Aggregation)
* **Définition** : Relation « tout-partie » où le composant peut **exister indépendamment** du conteneur. Si le conteneur est détruit, l'objet agrégé continue d'exister.
* **Mise en œuvre typique** : L'objet contenu est créé à l'extérieur puis **passé en paramètre** (via le constructeur ou un setter / Injection de dépendance).
* **Symbole UML** : Losange **blanc / vide (`◇`)** du côté du conteneur (le tout).

```java
// Exemple d'AGRÉGATION en Java
class Moteur {
    // Le moteur existe en tant qu'entité autonome
}

class Voiture {
    private Moteur moteur;

    // Le moteur est injecté depuis l'extérieur (reçu en argument)
    public Voiture(Moteur m) {
        this.moteur = m; 
    }
}
// Si l'objet Voiture est détruit, le Moteur existe toujours et peut être réutilisé ailleurs.
```

---

### 3. La Composition (« A-un » Forte / Part-Whole Composition)
* **Définition** : Relation « tout-partie » stricte avec **dépendance existentielle exclusive**. Le composant n'a pas de sens sans le conteneur : son cycle de vie dépend entièrement de lui. Si le conteneur est détruit, ses composants le sont également.
* **Mise en œuvre typique** : L'objet interne est **instancié directement à l'intérieur** de la classe hôte (`new` dans la déclaration de variable ou dans le constructeur).
* **Symbole UML** : Losange **noir / plein (`◆`)** du côté du conteneur (le tout).

```java
// Exemple de COMPOSITION en Java
class Coeur {
    // Le cœur ne peut pas vivre indépendamment du corps
}

class EtreHumain {
    // Instanciation interne exclusive : le coeur naît avec l'Humain
    private Coeur coeur = new Coeur(); 
}
// Si l'EtreHumain est détruit par le Garbage Collector, son Coeur est détruit aussi.
```

En **C++**, la composition s'exprime très naturellement par **valeur** (inclusion directe du membre dans l'objet) :
```cpp
// En C++ : Composition par valeur
class Moteur { /* ... */ };

class Voiture {
private:
    Moteur m; // Composition automatique : 'm' est alloué et détruit avec la Voiture
};
```

---

### 4. Tableau Synthétique des Relations (À mémoriser pour l'épreuve)

| Relation | Type de lien | Cycle de vie du composant | Exemple de code | Symbole UML |
| :--- | :--- | :--- | :--- | :---: |
| **Héritage** | « Est-un » (*is-a*) | Dérive de la classe mère | `class B extends A` | Flèche triangulaire creuse `──▷` |
| **Association** | « Utilise / Connaît » | Totalement indépendant | `void traiter(A a)` | Trait simple `───────` |
| **Agrégation** | « A-un » faible (*has-a*) | **Indépendant** (survit au tout) | `public C(A a) { this.a = a; }` | Losange vide `──◇` |
| **Composition** | « A-un » fort (*part-whole*) | **Dépendant** (détruit avec le tout) | `private C c = new C();` | Losange plein `──◆` |

---

### 5. Cas Pratique d'Examen (Concours CRMEF 2025 — Q21)

Soit le programme Java suivant :
```java
class A {
    private int x = 5;
    public int getX() { return x; }
}
class B extends A { }

class C {
    private A a;
    public C(A a) { this.a = a; } // Agrégation : 'a' est injecté de l'extérieur
}
class D {
    private C c = new C(new A()); // Composition : 'c' est créé exclusivement dans 'D'
}
```

* **Analyse de `B`** : `class B extends A` $\rightarrow$ **Héritage**.
* **Analyse de `C`** : Reçoit une référence vers `A` dans son constructeur $\rightarrow$ **Agrégation**.
* **Analyse de `D`** : `private C c = new C(new A());` $\rightarrow$ **Composition**, car l'instance de `C` est créée à l'intérieur de `D` et liée à sa durée de vie.

> **Principe de Conception (Design Pattern) :**
> *« Favoriser la composition plutôt que l'héritage » (Favor object composition over class inheritance)* : La composition offre un couplage plus faible, permet de modifier le comportement dynamiquement et évite les hiérarchies de classes rigides.

---

## 4. Comparatif Technique : Java vs C++

| Critère | Java | C++ |
| :--- | :--- | :--- |
| **Gestion Mémoire** | Automatique via Garbage Collector (GC) | Manuelle (`new` / `delete`) ou Pointeurs intelligents (`std::unique_ptr`, `std::shared_ptr`) |
| **Héritage Multiple** | Interdit pour les classes, autorisé via `interface` | Autorisé nativement entre classes (problème du diamant résolu par `virtual base class`) |
| **Pointeurs** | Références sécurisées (pas d'arithmétique de pointeurs) | Pointeurs explicites (`*`, `&`, arithmétique autorisée) |
| **Compilation & Exécution** | Bytecode exécuté par la JVM | Binaire compilé directement en code machine natif |
| **Méthodes Virtuelles** | Toutes les méthodes non-statiques sont virtuelles par défaut | Requiert explicitement le mot-clé `virtual` |
| **Destructeurs** | Pas de destructeur (méthode `finalize` dépréciée) | Destructeur explicite `~MaClasse()` fondamental pour libérer la mémoire (RAII) |

---

## 5. Pièges Classiques aux Concours CRMEF
1. **Confondre Surcharge (Overloading) et Redéfinition (Overriding)** :
   * *Overloading* : Même classe, même nom de méthode, **signatures différentes** (paramètres).
   * *Overriding* : Classe fille, **même signature exacte** que la méthode parente (`@Override`).
2. **Instanciation d'une classe abstraite** : `new MaClasseAbstraite()` provoque une erreur de compilation !
3. **Visibilité `protected`** :
   * **En Java** : Accessible par les classes filles ET toutes les classes du **même package**.
   * **En C++** : Accessible **uniquement** par la classe elle-même et ses classes dérivées.
4. **Constructeur par défaut** : Si vous ne déclarez aucun constructeur, le compilateur en génère un par défaut (sans arguments). Mais dès que vous déclarez un constructeur avec arguments, le constructeur par défaut disparaît (il faut le réécrire explicitement si besoin).
"""

POO_EXAMPLES = """### 1. Exemple Java : Encapsulation, Héritage et Polymorphisme
```java
public class Animal {
    protected String nom;
    public Animal(String nom) { this.nom = nom; }
    public void emettreSon() { System.out.println("Son d'animal"); }
}

public class Chien extends Animal {
    public Chien(String nom) { super(nom); }
    @Override
    public void emettreSon() { System.out.println("Wouf Wouf !"); }
}
```

### 2. Exemple Java : Différence Pratique entre Agrégation et Composition
```java
// AGRÉGATION : La Roue peut exister sans le Vélo (lien faible)
class Roue { String marque; }
class Velo {
    private Roue roueAvant;
    public Velo(Roue r) { this.roueAvant = r; } // Injectée depuis l'extérieur
}

// COMPOSITION : Le Processeur fait partie intégrante du Smartphone (lien fort)
class Processeur { int cœurs; }
class Smartphone {
    private Processeur cpu = new Processeur(); // Instancié directement à l'intérieur
}
```"""

POO_ASTUCES = """**Points clés incontournables pour le Concours :**
- **Composition vs Agrégation** :
  - **Composition (◆ Losange noir)** : L'objet interne est créé directement avec `new` dans la classe conteneur. Si le conteneur meurt, le composant meurt (dépendance forte).
  - **Agrégation (◇ Losange blanc)** : L'objet interne est transmis de l'extérieur via le constructeur ou une méthode. Il peut survivre à la destruction du conteneur (dépendance faible).
- **Héritage vs Composition** : En POO moderne, « favoriser la composition plutôt que l'héritage ».
- **En Java**, l'héritage multiple de classes est **interdit** (utilisez les `interface`).
- **Surcharge (Overloading)** = même classe, paramètres différents. **Redéfinition (Overriding)** = classe fille, même signature (`@Override`)."""

def enrich_course(apps, schema_editor):
    Course = apps.get_model('syllabus', 'Course')
    
    courses = Course.objects.filter(
        models.Q(title__icontains='Orientée Objet') |
        models.Q(title__icontains='POO') |
        models.Q(id=31)
    )

    for c in courses:
        c.content = POO_CONTENT
        c.examples = POO_EXAMPLES
        c.astuces = POO_ASTUCES
        if hasattr(c, 'content_fr'):
            c.content_fr = POO_CONTENT
        if hasattr(c, 'examples_fr'):
            c.examples_fr = POO_EXAMPLES
        if hasattr(c, 'astuces_fr'):
            c.astuces_fr = POO_ASTUCES
        c.save()

def reverse_enrich(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0004_course_astuces_ar_course_astuces_fr_and_more'),
    ]

    operations = [
        migrations.RunPython(enrich_course, reverse_code=reverse_enrich),
    ]
