# Generated by Django on 2026-10-05

from django.db import migrations, models

# ==============================================================================
# COURSE 33: PHP et SGBD MySQL
# ==============================================================================
PHP_CONTENT = r"""# Développement Dynamique Côté Serveur : PHP et SGBD MySQL

## 1. Introduction au Web Dynamique et à PHP

### A. Qu'est-ce que PHP ?
**PHP (Hypertext Preprocessor)** est un langage de script open-source **exécuté côté serveur** (*Server-Side*). 
Contrairement au HTML/CSS/JavaScript qui sont interprétés directement par le navigateur client, le code PHP est exécuté sur le serveur web (Apache, Nginx). Le serveur génère une page (généralement du HTML ou du JSON) qu'il renvoie ensuite au navigateur.

```
 Client (Navigateur)               Serveur Web (Apache/PHP)           SGBD (MySQL)
┌──────────────────┐               ┌───────────────────────┐         ┌────────────┐
│ 1. Requête HTTP  │──────────────>│ 2. Exécute script PHP │────────>│ 3. Requête │
│    (ex: page.php)│               │                       │<────────│    SQL     │
│ 4. Reçoit HTML   │<──────────────│ 3. Génère page HTML   │         └────────────┘
└──────────────────┘               └───────────────────────┘
```

### B. Balises et Syntaxe de Base
Tout bloc PHP est délimité par les balises `<?php` et `?>`. Chaque instruction se termine obligatoirement par un point-virgule (`;`).

```php
<?php
// Instruction d'affichage
echo "Bonjour le monde !";

// Si le fichier ne contient que du code PHP, il est recommandé d'omettre la balise fermante ?>
```

---

## 2. Les Fondamentaux du Langage PHP (De Zéro)

### A. Les Variables
* En PHP, toute variable commence obligatoirement par le symbole dollar **`$`** (ex: `$nom`, `$age`).
* **Sensibilité à la casse (*Case Sensitive*)** :
  * Les noms de **variables** sont **sensibles à la casse** (`$age` et `$Age` sont deux variables distinctes).
  * Les noms de **fonctions, méthodes et mots-clés** (`echo`, `if`, `while`, `function`) sont **insensibles à la casse**.
* Typage dynamique : Pas besoin de déclarer le type de la variable ; PHP le déduit automatiquement.

```php
<?php
$nom = "Karim";      // Chaîne de caractères (String)
$age = 24;           // Entier (Integer)
$moyenne = 15.75;    // Flottant (Float)
$estAdmis = true;    // Booléen (Boolean)
$valeur = null;      // Nul (NULL)
?>
```

### B. Chaînes de Caractères : Guillemets Simples vs Doubles
* **Guillemets simples `' '`** : Le texte est affiché tel quel, sans interprétation des variables.
* **Guillemets doubles `" "`** : Les variables sont **interpolées** (remplacées par leur valeur) et les caractères d'échappement (`\n`, `\t`) sont interprétés.
* **Concaténation** : L'opérateur de concaténation en PHP est le **point (`.`)** (et non le `+` comme en Java/JavaScript).

```php
<?php
$prenom = "Sara";

echo 'Bonjour $prenom';           // Affiche littéralement : Bonjour $prenom
echo "Bonjour $prenom";           // Affiche : Bonjour Sara
echo "Bonjour " . $prenom . " !"; // Concaténation avec le point
?>
```

---

## 3. Opérateurs Essentiels (Pièges Fréquents aux Concours)

### A. Égalité Souple (`==`) vs Égalité Stricte (`===`)
* **`==` (Égalité avec conversion de type)** : Compare les valeurs après conversion automatique.
  * `"5" == 5` $\rightarrow$ **TRUE**
  * `0 == ""` $\rightarrow$ **TRUE**
  * `0 == false` $\rightarrow$ **TRUE**
* **`===` (Égalité stricte)** : Compare la **valeur ET le type**. Aucune conversion n'est faite.
  * `"5" === 5` $\rightarrow$ **FALSE** (String vs Integer)
  * `0 === false` $\rightarrow$ **FALSE** (Integer vs Boolean)

### B. Opérateur de Coalescence Nulle (`??`) — *(Examen 2025 - Q24)*
* L'opérateur **`$a ?? $b`** renvoie `$a` s'il existe et **n'est pas `null`**, sinon il renvoie `$b`.
* Il est équivalent à : `isset($a) ? $a : $b`.

```php
<?php
$x = null;
$y = 0;
$z = 'valeur';

echo $x ?? $y ?? $z ?? 'aucun';
// Résultat : 0 (car $x est null, mais $y vaut 0, et 0 n'est pas null !)
?>
```

### C. Opérateur Vaisseau Spatial / Spaceship (`<=>`)
Introduit en PHP 7 pour faciliter le tri :
* `$a <=> $b` retourne :
  * **`-1`** si `$a < $b`
  * **`0`** si `$a == $b`
  * **`1`** si `$a > $b`

---

## 4. Les Tableaux en PHP (Arrays)

En PHP, les tableaux sont des tables de hachage ordonnées extrêmement polyvalentes.

### A. Tableaux Indexés Numériquement
```php
<?php
// Déclaration avec la syntaxe courte []
$notes = [14, 16, 18, 12];

// Accès par indice (commence à 0)
echo $notes[0]; // 14

// Ajouter un élément à la fin
$notes[] = 20; // Équivalent à array_push($notes, 20)
?>
```

### B. Tableaux Associatifs (Clé $\rightarrow$ Valeur)
Les clés sont des chaînes de caractères au lieu de nombres :
```php
<?php
$candidat = [
    "cin" => "AB12345",
    "nom" => "Ouakrim",
    "specialite" => "Informatique",
    "note" => 17.5
];

// Accès via la clé
echo $candidat["nom"]; // Ouakrim
?>
```

### C. Fonctions Indispensables sur les Tableaux
| Fonction | Description | Exemple |
| :--- | :--- | :--- |
| `count($tab)` | Nombre d'éléments | `count($notes)` |
| `in_array($val, $tab)` | Vérifie si une valeur existe dans le tableau | `in_array(18, $notes)` |
| `array_key_exists($cle, $tab)` | Vérifie si une clé existe | `array_key_exists('cin', $candidat)` |
| `array_merge($t1, $t2)` | Fusionne deux tableaux | `array_merge($a, $b)` |
| `sort($tab)` / `rsort($tab)` | Trie un tableau indexé (croissant / décroissant) | `sort($notes)` |
| `asort($tab)` / `ksort($tab)` | Trie associatif (par valeur / par clé) | `ksort($candidat)` |

---

## 5. Structures de Contrôle et Boucles

### A. Conditions : `if / elseif / else`
```php
<?php
if ($note >= 16) {
    echo "Très Bien";
} elseif ($note >= 10) {
    echo "Admis";
} else {
    echo "Ajourné";
}
?>
```

### B. La Boucle `foreach` (La plus utilisée en PHP)
Permet de parcourir facilement n'importe quel tableau sans gérer d'indice manuel :
```php
<?php
// Parcours valeur seule
foreach ($notes as $n) {
    echo "Note : $n <br>";
}

// Parcours clé => valeur
foreach ($candidat as $cle => $valeur) {
    echo "$cle : $valeur <br>";
}
?>
```

---

## 6. Les Fonctions et Portée des Variables

### A. Déclaration de Fonction
```php
<?php
function calculerMoyenne(float $n1, float $n2): float {
    return ($n1 + $n2) / 2;
}

echo calculerMoyenne(14.5, 17.5); // 16
?>
```

### B. Passage par Valeur vs par Référence (`&`)
* Par défaut, les arguments sont passés **par valeur** (une copie est transmise).
* Pour modifier directement la variable d'origine, on utilise le symbole **`&`** (passage par référence).

```php
<?php
function ajouterBonus(&$note) {
    $note += 2; // Modifie directement la variable d'origine
}

$maNote = 14;
ajouterBonus($maNote);
echo $maNote; // Affiche 16 !
?>
```

### C. Portée Locale vs Globale (`global`)
En PHP, une variable déclarée en dehors d'une fonction n'est **pas accessible** à l'intérieur sans le mot-clé `global` :
```php
<?php
$site = "Inforéussit";

function afficherSite() {
    global $site; // Obligatoire pour accéder à la variable externe
    echo $site;
}
?>
```

---

## 7. Formulaires Web et Superglobales

Les **Superglobales** sont des variables prédéfinies disponibles dans tous les contextes d'exécution sans déclaration préalable.

### A. `$_GET` vs `$_POST` (Question Classique Concours)

| Critère | Méthode GET (`$_GET`) | Méthode POST (`$_POST`) |
| :--- | :--- | :--- |
| **Transmission** | Visible dans l'URL (`page.php?id=5&nom=test`) | Invisible dans l'URL (dans le corps de la requête HTTP) |
| **Taille des données** | Limitée par la longueur max de l'URL (~2048 caractères) | Quasi-illimitée (paramétrable via `post_max_size` dans `php.ini`) |
| **Mise en favori / Historique** | Oui, peut être partagée et mise en signet | Non, recharger la page demande confirmation |
| **Sécurité** | À proscrire pour données sensibles (mots de passe, cartes) | Obligatoire pour formulaires d'authentification et fichiers |
| **Idéal pour** | Recherches, filtrages, pagination | Inscriptions, connexions, paiements, upload de fichiers |

### B. Traitement Sécurisé d'un Formulaire
```php
<?php
// Vérifier si le formulaire a été soumis en POST
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Vérifier l'existence et nettoyer les données contre les failles XSS
    $email = isset($_POST['email']) ? htmlspecialchars(trim($_POST['email'])) : '';
    $pass  = $_POST['password'] ?? '';

    if (empty($email) || empty($pass)) {
        echo "Tous les champs sont obligatoires.";
    } else {
        // Traitement (vérification en BDD, session...)
    }
}
?>
```

### C. Différence entre `isset()`, `empty()` et `is_null()`
* **`isset($v)`** : Retourne `true` si la variable est déclarée et **différente de `null`**.
* **`empty($v)`** : Retourne `true` si la variable n'existe pas ou si sa valeur est considérée comme vide (`""`, `0`, `0.0`, `"0"`, `null`, `false`, `[]`).
* **`is_null($v)`** : Retourne `true` uniquement si la valeur est strictement `null`.

---

## 8. Gestion des Sessions et des Cookies

Le protocole HTTP étant **sans état (*Stateless*)**, les sessions et cookies permettent de conserver l'état de connexion de l'utilisateur entre différentes pages.

### A. Les Sessions (`$_SESSION`)
* Les données de session sont conservées **côté serveur** (sécurisées).
* Un identifiant unique (`PHPSESSID`) est envoyé au navigateur via un cookie temporaire.
* **Règle absolue** : `session_start()` doit obligatoirement être appelé **tout en haut du script**, avant le moindre affichage ou espace HTML.

```php
<?php
session_start(); // Initialise ou restaure la session

// Stocker des données de session
$_SESSION['user_id'] = 42;
$_SESSION['role'] = 'Candidat';

// Détruire la session (déconnexion)
session_unset();   // Vide les variables
session_destroy(); // Détruit le fichier de session serveur
?>
```

### B. Les Cookies (`$_COOKIE`)
* Les cookies sont stockés **côté client** (dans le navigateur de l'internaute).
* Création avec `setcookie(nom, valeur, expiration, chemin)`.
* Taille maximale : **4 Ko** par cookie.

---

## 9. Inclusion de Fichiers : `include` vs `require`

| Instruction | Si le fichier est manquant | Cas d'utilisation |
| :--- | :--- | :--- |
| **`include 'fichier.php'`** | Émet un simple avertissement (`E_WARNING`) et **continue l'exécution du script** | Fichiers secondaires (bannières, pied de page facultatif) |
| **`require 'fichier.php'`** | Émet une erreur fatale (`E_COMPILE_ERROR`) et **stoppe immédiatement le script** | Fichiers vitaux (connexion BDD, fonctions de sécurité) |
| **`include_once` / `require_once`** | Même comportement, mais garantit que le fichier ne sera inclus **qu'une seule fois** (évite les erreurs de redéclaration de fonctions/classes) | Fichiers de classes, librairies de fonctions |

---

## 10. Accès aux Bases de Données MySQL avec PDO

**PDO (PHP Data Objects)** est l'interface standard et sécurisée pour communiquer avec les SGBD relationnels en PHP.

### A. Connexion Sécurisée à MySQL
```php
<?php
$host = 'localhost';
$dbname = 'concours_db';
$username = 'root';
$password = '';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname;charset=utf8mb4", $username, $password, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,        // Lève des exceptions en cas d'erreur SQL
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,  // Résultats sous forme de tableaux associatifs
        PDO::ATTR_EMULATE_PREPARES => false                // Utilise les vraies requêtes préparées du serveur
    ]);
} catch (PDOException $e) {
    die("Erreur de connexion : " . $e->getMessage());
}
?>
```

### B. Requêtes Préparées (Protection Absolue contre l'Injection SQL)
Ne **JAMAIS** concaténer des variables utilisateurs directement dans une requête SQL !

```php
<?php
// ❌ MAUVAIS (Vulnérable à l'Injection SQL !)
// $pdo->query("SELECT * FROM users WHERE email = '" . $_POST['email'] . "'");

// ✅ BON (Requête préparée avec marqueurs nommés)
$sql = "SELECT id, nom, mot_de_passe FROM candidats WHERE email = :email";
$stmt = $pdo->prepare($sql);

// Exécution avec tableau de paramètres sécurisés
$stmt->execute([
    'email' => $_POST['email']
]);

// Récupération d'un seul résultat
$candidat = $stmt->fetch();

// Récupération de tous les résultats
// $tousLesCandidats = $stmt->fetchAll();
?>
```

---

## 11. Sécurité Web Fondamentale (Top Failles OWASP)

1. **Injection SQL** :
   * *Risque* : Vol, modification ou suppression de la base de données.
   * *Solution* : Toujours utiliser des **requêtes préparées PDO** (`prepare()` + `execute()`).
2. **XSS (Cross-Site Scripting)** :
   * *Risque* : Injection de scripts JavaScript malveillants dans une page web pour voler les cookies de session des utilisateurs.
   * *Solution* : Échapper systématiquement les données avant affichage HTML avec `htmlspecialchars($str, ENT_QUOTES, 'UTF-8')`.
3. **Hachage Sécurisé des Mots de Passe** :
   * Ne jamais utiliser `md5()` ou `sha1()` (obsolètes et cassables instantanément).
   * Utiliser l'API native de PHP :
   ```php
   // Hachage sécurisé (BCrypt par défaut avec Salt automatique)
   $hash = password_hash($motDePasseClair, PASSWORD_DEFAULT);

   // Vérification lors de la connexion
   if (password_verify($motDePasseSaisi, $hash)) {
       // Connexion réussie !
   }
   ```
4. **CSRF (Cross-Site Request Forgery)** :
   * *Solution* : Générer un jeton aléatoire unique (`token`) stocké en session et vérifié dans chaque formulaire POST.

---

## 12. Architecture MVC (Modèle - Vue - Contrôleur)
* **Modèle (Model)** : Gère les données et les requêtes SQL vers la base.
* **Vue (View)** : Fichier d'affichage contenant le HTML/CSS.
* **Contrôleur (Controller)** : Reçoit la requête de l'utilisateur, interroge le Modèle et charge la Vue appropriée.
"""

PHP_EXAMPLES = r"""### 1. Exemple PHP : Traitement de Formulaire et Sécurité XSS
```php
<?php
// Nettoyage et validation d'une saisie utilisateur
if ($_SERVER["REQUEST_METHOD"] === "POST") {
    $pseudo = htmlspecialchars(trim($_POST["pseudo"] ?? ""));
    $email  = filter_var($_POST["email"] ?? "", FILTER_VALIDATE_EMAIL);

    if ($email === false) {
        echo "Format d'adresse e-mail invalide.";
    } else {
        echo "Bienvenue, " . $pseudo;
    }
}
?>
```

### 2. Exemple PDO : Insertion Sécurisée en Base de Données
```php
<?php
$stmt = $pdo->prepare("INSERT INTO candidats (nom, email, note) VALUES (:nom, :email, :note)");
$stmt->execute([
    'nom'   => $nom,
    'email' => $email,
    'note'  => $note
]);
$nouveauId = $pdo->lastInsertId();
?>
```"""

PHP_ASTUCES = r"""**Points clés incontournables pour le Concours :**
- **Concaténation** : en PHP, c'est le point (`.`), pas le `+` !
- **Guillemets** : les variables s'interprètent dans `"..."`, mais restent du texte brut dans `'...'`.
- **`include` vs `require`** : `include` continue sur avertissement, `require` stoppe sur erreur fatale.
- **`==` vs `===`** : `"0" == false` est VRAI, mais `"0" === false` est FAUX.
- **`session_start()`** doit obligatoirement être appelé avant tout envoi de contenu HTML.
- **Injection SQL** : la parade absolue est la **requête préparée** (`prepare()` + `execute()`)."""


# ==============================================================================
# COURSE 32: HTML5, CSS3, JavaScript
# ==============================================================================
FRONTEND_CONTENT = r"""# Technologies Web Côté Client (Front-End) : HTML5, CSS3, JavaScript

## 1. Introduction au Front-End : Le Triptyque Web

Une page web moderne repose sur trois technologies complémentaires :
* **HTML5 (Structure & Sémantique)** : Le squelette de la page (textes, images, formulaires, liens).
* **CSS3 (Présentation & Mise en page)** : L'habillage visuel (couleurs, typographies, grilles, animations).
* **JavaScript (Comportement & Dynamicité)** : Le système nerveux (interactivité, requêtes asynchrones, manipulation du DOM).

---

## 2. HTML5 : De Zéro à la Structuration Sémantique

### A. Anatomie d'un Document HTML5
Tout document HTML commence par la déclaration de type et contient deux parties principales : `<head>` (métadonnées) et `<body>` (contenu visible).

```html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Préparation Concours CRMEF</title>
</head>
<body>
    <h1>Bienvenue sur Inforéussit</h1>
    <p>Plateforme nationale de préparation aux concours.</p>
</body>
</html>
```

### B. Balises de Contenu Essentielles
* **Titres** : `<h1>` (titre principal unique de la page) jusqu'à `<h6>` (sous-titres de niveau 6).
* **Texte** : `<p>` (paragraphe), `<strong>` (importance forte / gras sémantique), `<em>` (emphase / italique), `<code>` (code).
* **Liens et Médias** :
  * `<a href="https://example.com" target="_blank">Lien</a>` : Hyperlien.
  * `<img src="image.png" alt="Description obligatoire pour l'accessibilité">` : Image.
* **Listes** :
  * `<ul><li>Élément</li></ul>` : Liste non ordonnée (à puces).
  * `<ol><li>Élément</li></ol>` : Liste ordonnée (numérotée).

### C. Balises Sémantiques HTML5 (Question Fréquente aux Concours)
HTML5 introduit des balises ayant une signification structurelle claire pour le SEO (référencement) et l'accessibilité :
* `<header>` : En-tête de la page ou d'une section.
* `<nav>` : Liens principaux de navigation.
* `<main>` : Contenu principal unique de la page (ne doit pas être répété).
* `<article>` : Bloc autonome et distribuable indépendamment (ex: article de blog, fiche produit).
* `<section>` : Regroupement thématique de contenu au sein d'une page.
* `<aside>` : Contenu secondaire ou latéral (barre latérale, encadré lié).
* `<footer>` : Pied de page (droits d'auteur, mentions légales, liens secondaires).

### D. Formulaires HTML5 et Validation Native
```html
<form action="/traitement.php" method="POST">
    <label for="email">Adresse E-mail :</label>
    <input type="email" id="email" name="email" required placeholder="nom@domaine.com">

    <label for="age">Âge :</label>
    <input type="number" id="age" name="age" min="18" max="60">

    <button type="submit">Valider</button>
</form>
```

---

## 3. CSS3 : Des Sélecteurs au Responsive Design

### A. Sélecteurs CSS et Calcul de Spécificité (Crucial aux Concours !)
Lorsqu'un même élément reçoit plusieurs règles conflictuelles, le navigateur applique la règle ayant la **spécificité (poids)** la plus élevée :

```
!important > Style Inline (1000) > ID (100) > Classe/Attribut/Pseudo-classe (10) > Élément (1)
```

* Sélecteur d'élément : `p { color: black; }` (Poids : 1)
* Sélecteur de classe : `.texte { color: blue; }` (Poids : 10)
* Sélecteur d'ID : `#titre { color: red; }` (Poids : 100)
* Sélecteur combiné : `div.card #btn:hover` $\rightarrow$ 1 element (1) + 1 class (10) + 1 ID (100) + 1 pseudo-class (10) = Poids 121.

### B. Le Modèle de Boîte (Box Model)
Chaque élément HTML est représenté par une boîte rectangulaire constituée de :
1. **Content** : Le contenu réel (texte, image).
2. **Padding** : La marge interne (entre le contenu et la bordure).
3. **Border** : La bordure entourant l'élément.
4. **Margin** : La marge externe (espace séparant l'élément de ses voisins).

> **Règle d'or moderne** : `box-sizing: border-box;` fait en sorte que `width: 200px` inclue le padding et la bordure, évitant que la boîte ne déborde !

### C. Mise en Page Moderne : Flexbox vs CSS Grid

| Critère | Flexbox (`display: flex`) | CSS Grid (`display: grid`) |
| :--- | :--- | :--- |
| **Dimension** | **Unidimensionnel (1D)** : En ligne OU en colonne | **Bidimensionnel (2D)** : Lignes ET colonnes simultanées |
| **Propriétés Clés** | `justify-content` (axe principal), `align-items` (axe secondaire), `gap` | `grid-template-columns: repeat(3, 1fr);`, `gap` |
| **Cas d'usage** | Barres de navigation, boutons alignés, listes simples | Grilles de cartes, gabarits complets de page |

```css
/* Exemple Flexbox */
.navbar {
    display: flex;
    justify-content: space-between; /* Écarte les extrémités */
    align-items: center;            /* Centre verticalement */
    gap: 16px;
}

/* Exemple CSS Grid */
.grille-cours {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
    gap: 20px;
}
```

### D. Responsive Design et Media Queries
Permet d'adapter l'affichage selon la taille de l'écran :
```css
/* Style par défaut pour ordinateur */
.sidebar { width: 300px; display: block; }

/* Adaptation tablette et mobile */
@media (max-width: 768px) {
    .sidebar {
        display: none; /* Masqué sur petit écran */
    }
}
```

---

## 4. JavaScript (ES6+) : De Zéro au DOM Dynamique

### A. Déclaration de Variables : `var` vs `let` vs `const` — *(Examen 2025 - Q25)*

| Mot-clé | Portée (*Scope*) | Réassignable | Hoisting & Temporal Dead Zone (TDZ) |
| :--- | :--- | :--- | :--- |
| **`var`** | Fonctionnelle (*Function-scoped*) | Oui | Remontée en haut de fonction avec valeur `undefined`. |
| **`let`** | Bloc (*Block-scoped* `{}`) | Oui | Soumis à la **TDZ** : l'accès avant déclaration lève une `ReferenceError` ! |
| **`const`** | Bloc (*Block-scoped* `{}`) | Non | Soumis à la **TDZ**, doit être initialisée dès la déclaration. |

```javascript
// Piège classique du concours (Q25) :
let x = 5;
function test() {
    console.log(x); // ❌ ReferenceError (Cannot access 'x' before initialization)
    let x = 10;     // La variable 'x' locale existe dans le bloc mais n'est pas encore initialisée !
}
test();
```

### B. Opérateurs de Comparaison : `==` vs `===`
* `==` : Égalité avec conversion automatique de type (`5 == "5"` est **vrai**).
* `===` : Égalité stricte sans conversion (`5 === "5"` est **faux** car `number !== string`).

### C. Fonctions Fléchées (*Arrow Functions*)
```javascript
// Fonction classique
function additionner(a, b) {
    return a + b;
}

// Fonction fléchée moderne
const additionner = (a, b) => a + b;
// Particularité : elle ne possède pas son propre 'this' (conserve le 'this' englobant).
```

### D. Méthodes Modernes de Tableaux
```javascript
const nombres = [1, 2, 3, 4, 5];

// 1. map() : transforme chaque élément
const doubles = nombres.map(n => n * 2); // [2, 4, 6, 8, 10]

// 2. filter() : sélectionne selon condition
const pairs = nombres.filter(n => n % 2 === 0); // [2, 4]

// 3. reduce() : accumule en une valeur unique
const somme = nombres.reduce((acc, n) => acc + n, 0); // 15
```

---

## 5. Manipulation du DOM et Événements

Le **DOM (Document Object Model)** est la représentation en arbre hiérarchique des éléments HTML en mémoire.

### A. Sélection et Modification d'Éléments
```javascript
// Sélection
const titre = document.querySelector('#mon-titre');
const boutons = document.querySelectorAll('.btn');

// Modification de contenu et style
titre.textContent = "Nouveau Titre";
titre.classList.add('active'); // Ajoute une classe CSS
```

### B. Écouteurs d'Événements et Propagation
```javascript
const btn = document.querySelector('#submit-btn');

btn.addEventListener('click', (event) => {
    event.preventDefault();  // Empêche l'action par défaut (ex: rechargement formulaire)
    event.stopPropagation(); // Stoppe la propagation de l'événement vers les parents
    console.log("Bouton cliqué !");
});
```

* **Phases de propagation d'un événement** :
  1. **Phase de Capture** : L'événement descend depuis `window` jusqu'à l'élément cible.
  2. **Phase Cible** : L'événement atteint l'élément déclencheur.
  3. **Phase de Bouillonnement (*Bubbling*)** : L'événement remonte depuis l'élément cible vers `window`.

---

## 6. Asynchronisme : Promesses et Async / Await

JavaScript est **monothreadé** : il exécute une seule tâche à la fois grâce à son **Event Loop** (boucle d'événements). Pour ne pas bloquer l'interface pendant un appel réseau, on utilise l'asynchronisme.

```javascript
// Utilisation moderne d'async / await avec l'API Fetch
async function chargerCandidats() {
    try {
        const response = await fetch('/api/candidats/');
        if (!response.ok) {
            throw new Error(`Erreur HTTP : ${response.status}`);
        }
        const data = await response.json();
        console.log("Candidats reçus :", data);
    } catch (erreur) {
        console.error("Échec du chargement :", erreur);
    }
}
```

---

## 7. Stockage Côté Client : LocalStorage vs SessionStorage vs Cookies

| Mécanisme | Capacité | Durée de vie | Accessible par |
| :--- | :--- | :--- | :--- |
| **`localStorage`** | ~5 à 10 Mo | Permanente (jusqu'à suppression explicite par code ou utilisateur) | Client uniquement (JavaScript) |
| **`sessionStorage`** | ~5 Mo | Durée de l'onglet actif (effacé à la fermeture de l'onglet) | Client uniquement (JavaScript) |
| **`Cookies`** | ~4 Ko | Définie par date d'expiration (`Expires / Max-Age`) | Client ET Serveur (transmis automatiquement dans chaque en-tête HTTP) |
"""

FRONTEND_EXAMPLES = r"""### 1. Exemple CSS : Centrage Parfait avec Flexbox
```css
.conteneur-centre {
    display: flex;
    justify-content: center; /* Centrage horizontal */
    align-items: center;     /* Centrage vertical */
    min-height: 100vh;
}
```

### 2. Exemple JavaScript : Requête Asynchrone et Rendu DOM
```javascript
document.querySelector('#btn-charger').addEventListener('click', async () => {
    const conteneur = document.querySelector('#resultats');
    conteneur.innerHTML = "Chargement en cours...";
    
    try {
        const res = await fetch('https://api.example.com/notes');
        const notes = await res.json();
        conteneur.innerHTML = notes.map(n => `<p>Note : ${n.valeur}/20</p>`).join('');
    } catch (err) {
        conteneur.innerHTML = "Erreur de chargement.";
    }
});
```"""

FRONTEND_ASTUCES = r"""**Points clés incontournables pour le Concours :**
- **Sélecteurs CSS** : ID (`#`) a plus de poids que la classe (`.`), qui a plus de poids que la balise (`div`).
- **`box-sizing: border-box`** : toujours l'utiliser pour éviter que padding et border n'agrandissent les dimensions de la boîte.
- **`var` vs `let`** : `let` a une portée de bloc et lève une `ReferenceError` si accédé avant déclaration (**Temporal Dead Zone**).
- **`==` vs `===`** : toujours privilégier `===` pour tester l'égalité stricte sans conversion implicite.
- **`localStorage`** conserve les données même après fermeture du navigateur, contrairement à `sessionStorage`."""


def update_web_courses(apps, schema_editor):
    Course = apps.get_model('syllabus', 'Course')

    # 1. Update PHP course (id=33 or title containing PHP)
    php_courses = Course.objects.filter(models.Q(id=33) | models.Q(title__icontains='PHP'))
    for c in php_courses:
        c.content = PHP_CONTENT
        c.examples = PHP_EXAMPLES
        c.astuces = PHP_ASTUCES
        if hasattr(c, 'content_fr'):
            c.content_fr = PHP_CONTENT
        if hasattr(c, 'examples_fr'):
            c.examples_fr = PHP_EXAMPLES
        if hasattr(c, 'astuces_fr'):
            c.astuces_fr = PHP_ASTUCES
        c.save()

    # 2. Update Front-End course (id=32 or title containing HTML5 or Web côté client)
    frontend_courses = Course.objects.filter(models.Q(id=32) | models.Q(title__icontains='HTML5') | models.Q(title__icontains='côté client'))
    for c in frontend_courses:
        c.content = FRONTEND_CONTENT
        c.examples = FRONTEND_EXAMPLES
        c.astuces = FRONTEND_ASTUCES
        if hasattr(c, 'content_fr'):
            c.content_fr = FRONTEND_CONTENT
        if hasattr(c, 'examples_fr'):
            c.examples_fr = FRONTEND_EXAMPLES
        if hasattr(c, 'astuces_fr'):
            c.astuces_fr = FRONTEND_ASTUCES
        c.save()

def reverse_update(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_enrich_poo_course_composition'),
    ]

    operations = [
        migrations.RunPython(update_web_courses, reverse_code=reverse_update),
    ]
