# Generated by Django on 2026-10-05

from django.db import migrations

SQL_CONTENT = r"""# 02. Bases de Données Relationnelles et Langage SQL

Bienvenue dans ce cours complet sur les **Bases de Données Relationnelles** et le **Langage SQL** (*Structured Query Language*). Ce guide est conçu pour vous emmener **du niveau débutant absolu jusqu'au niveau intermédiaire / avancé**, avec des explications claires, des exemples visuels et les notions indispensables pour réussir les concours (CRMEF, Enseignement, Ingénierie d'État).

---

## 1. Introduction aux Bases de Données Relationnelles (SGBDR)

### A. Qu'est-ce qu'une Base de Données ?
Une **base de données (BDD)** est un ensemble structuré et organisé d'informations persistantes, stockées sur un support informatique permanent (disque dur, SSD), conçu pour être interrogé et modifié facilement et simultanément par plusieurs utilisateurs ou applications.

Un **SGBD (Système de Gestion de Base de Données)** ou **DBMS** en anglais, est le logiciel serveur qui assure le stockage, la sécurité, les sauvegardes et l'accès aux données.
* Exemples de SGBD Relationnels populaires : **PostgreSQL**, **MySQL**, **Oracle**, **SQL Server**, **SQLite**, **MariaDB**.

### B. Le Modèle Relationnel (Concepts Clés)
Introduit par **Edgar F. Codd** en 1970, le modèle relationnel organise toutes les données sous forme de **tables** (appelées mathématiquement *relations*).

```
 Table: EMPLOYES (Relation)
┌────┬──────────────┬─────────────┬───────────┬─────────────┐
│ id │ nom          │ poste       │ salaire   │ dept_id     │  <-- Colonnes (Champs / Attributs)
├────┼──────────────┼─────────────┼───────────┼─────────────┤
│ 1  │ Ouakrim Rida │ Développeur │  12000.00 │ 10          │  <-- Ligne (Enregistrement / Tuple)
│ 2  │ Sara Alami   │ RH          │   9500.00 │ 20          │
│ 3  │ Mehdi Bennani│ Data Analyst│  11000.00 │ 10          │
└────┴──────────────┴─────────────┴───────────┴─────────────┘
```

1. **Table (Relation)** : Une grille à deux dimensions composée de colonnes et de lignes.
2. **Colonne (Attribut ou Champ)** : Une caractéristique commune à tous les enregistrements (ex: `nom`, `salaire`), typée rigoureusement (`INT`, `VARCHAR`, `DATE`...).
3. **Ligne (Enregistrement ou Tuple)** : Une occurrence unique d'une entité (ex: l'employé Rida).
4. **Clé Primaire (Primary Key - PK)** :
   * Une colonne (ou groupe de colonnes) qui identifie **de façon unique et certaine** chaque ligne de la table.
   * Propriétés obligatoires : **Unique** et **Non nulle (`NOT NULL`)**.
   * Exemple : `id` ou `code_national_cnie`.
5. **Clé Étrangère (Foreign Key - FK)** :
   * Une colonne dans une table enfant qui fait référence à la **clé primaire** d'une autre table parente.
   * Elle matérialise l'association ou la relation entre deux tables.
   * Exemple : `dept_id` dans la table `EMPLOYES` fait référence à `id` dans la table `DEPARTEMENTS`.
6. **Intégrité Référentielle** :
   * Règle de cohérence qui garantit qu'une clé étrangère ne peut pas pointer vers une ligne inexistante dans la table parente.

---

## 2. Le Langage SQL et ses Familles d'Instructions

Le **SQL (Structured Query Language)** est un langage déclaratif : vous décrivez **ce que vous voulez obtenir**, et le moteur de base de données détermine **comment** l'exécuter de façon optimale.

Le SQL se divise en 4 sous-familles principales :
1. **DDL / LDD (Data Definition Language)** : Définit et modifie la structure des objets (`CREATE`, `ALTER`, `DROP`, `TRUNCATE`).
2. **DML / LMD (Data Manipulation Language)** : Manipule les données existantes (`INSERT`, `UPDATE`, `DELETE`).
3. **DQL / LRD (Data Query Language)** : Interroge et extrait les données (`SELECT`).
4. **DCL / TCL** : Contrôle des accès (`GRANT`, `REVOKE`) et gestion des transactions (`COMMIT`, `ROLLBACK`).

---

## 3. DDL (Data Definition Language) : Définir la Structure

### A. Types de Données Standards
* **Nombres** : `INT` / `INTEGER`, `BIGINT`, `SMALLINT`, `DECIMAL(precision, echelle)` / `NUMERIC` (idéal pour la monnaie, ex: `DECIMAL(10, 2)`).
* **Textes** : `VARCHAR(n)` (chaîne de taille variable, max `n` caractères), `CHAR(n)` (taille fixe), `TEXT` (textes longs illimités).
* **Dates & Heures** : `DATE` (`AAAA-MM-JJ`), `TIME` (`HH:MM:SS`), `DATETIME` ou `TIMESTAMP` (date + heure avec fuseau horaire).
* **Booléens** : `BOOLEAN` (`TRUE` ou `FALSE`).

### B. Créer une Table (`CREATE TABLE`) et les Contraintes
Les contraintes garantissent la validité des données :
* `PRIMARY KEY` : Clé primaire (identifiant unique, indexé).
* `NOT NULL` : Interdit la valeur vide/nulle.
* `UNIQUE` : Interdit les doublons dans cette colonne.
* `DEFAULT valeur` : Attribue une valeur par défaut si rien n'est fourni.
* `CHECK (condition)` : Vérifie une règle métier (ex: `CHECK (salaire > 0)`).
* `FOREIGN KEY ... REFERENCES ...` : Établit le lien avec une table parente.

```sql
-- Création de la table des départements
CREATE TABLE departements (
    id INT PRIMARY KEY AUTO_INCREMENT, -- En PostgreSQL: id SERIAL PRIMARY KEY
    nom VARCHAR(50) NOT NULL UNIQUE,
    lieu VARCHAR(100) DEFAULT 'Casablanca'
);

-- Création de la table des employés avec clé étrangère
CREATE TABLE employes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE,
    poste VARCHAR(50) NOT NULL,
    salaire DECIMAL(10, 2) CHECK (salaire >= 3000),
    date_embauche DATE NOT NULL,
    dept_id INT,
    
    -- Définition de la clé étrangère avec intégrité référentielle
    CONSTRAINT fk_employe_dept 
        FOREIGN KEY (dept_id) 
        REFERENCES departements(id) 
        ON DELETE SET NULL 
        ON UPDATE CASCADE
);
```

> **Options sur `ON DELETE` / `ON UPDATE` :**
> * `CASCADE` : Si le département 10 est supprimé, tous ses employés sont automatiquement supprimés.
> * `SET NULL` : Si le département 10 est supprimé, le champ `dept_id` des employés passe à `NULL`.
> * `RESTRICT` ou `NO ACTION` (défaut) : Empêche la suppression d'un département tant qu'il contient des employés.

### C. Modifier une Table (`ALTER TABLE`)
```sql
-- Ajouter une nouvelle colonne
ALTER TABLE employes ADD COLUMN telephone VARCHAR(20);

-- Modifier le type d'une colonne
ALTER TABLE employes MODIFY COLUMN poste VARCHAR(80); -- PostgreSQL: ALTER TABLE employes ALTER COLUMN poste TYPE VARCHAR(80);

-- Renommer une colonne
ALTER TABLE employes RENAME COLUMN lieu TO ville;

-- Supprimer une colonne
ALTER TABLE employes DROP COLUMN telephone;
```

### D. Supprimer une Table (`DROP` vs `TRUNCATE`)
* **`DROP TABLE employes;`** : Supprime complètement la table, sa structure, ses données et ses index. La table n'existe plus du tout.
* **`TRUNCATE TABLE employes;`** : Vide **toutes les lignes** de la table d'un seul coup mais conserve la structure vide intacte. Réinitialise le compteur d'auto-incrément. Beaucoup plus rapide qu'un `DELETE FROM`.

---

## 4. DML (Data Manipulation Language) : Insérer, Modifier, Supprimer

### A. Insérer des Lignes (`INSERT INTO`)
```sql
-- Insertion d'une ligne complète
INSERT INTO departements (nom, lieu) 
VALUES ('Informatique', 'Rabat');

-- Insertion multiple en une seule requête (Performant)
INSERT INTO employes (nom, prenom, email, poste, salaire, date_embauche, dept_id) 
VALUES 
('Ouakrim', 'Rida', 'rida@example.com', 'Lead Dev', 15000.00, '2022-01-15', 1),
('Alami', 'Sara', 'sara@example.com', 'RH Manager', 12000.00, '2021-06-01', 2),
('Bennani', 'Mehdi', 'mehdi@example.com', 'Data Analyst', 11000.00, '2023-03-10', 1);
```

### B. Mettre à Jour des Lignes (`UPDATE ... SET`)
⚠️ **Règle vitale** : N'oubliez JAMAIS la clause `WHERE`, sinon **toutes les lignes** de la table seront modifiées !
```sql
-- Augmenter de 10% le salaire de Rida Ouakrim
UPDATE employes 
SET salaire = salaire * 1.10 
WHERE id = 1;

-- Changer le poste et le département
UPDATE employes 
SET poste = 'Senior Dev', dept_id = 1 
WHERE email = 'rida@example.com';
```

### C. Supprimer des Lignes (`DELETE FROM`)
⚠️ Sans `WHERE`, toutes les lignes sont supprimées !
```sql
-- Supprimer un employé spécifique
DELETE FROM employes 
WHERE id = 3;

-- Supprimer tous les employés d'un département donné
DELETE FROM employes 
WHERE dept_id = 2;
```

---

## 5. DQL (Data Query Language) : L'Art de l'Interrogation (`SELECT`)

La commande **`SELECT`** est le cœur battant du SQL.

### A. Structure de Base
```sql
SELECT colonnes
FROM table
WHERE conditions;
```

```sql
-- Sélectionner toutes les colonnes
SELECT * FROM employes;

-- Sélectionner des colonnes spécifiques avec renommage (Alias avec AS)
SELECT nom, prenom, salaire AS remuneration_mensuelle 
FROM employes;

-- Éliminer les doublons avec DISTINCT
SELECT DISTINCT poste FROM employes;
```

### B. Filtrer avec `WHERE` et les Opérateurs
* **Comparaison** : `=`, `<>`, `!=`, `>`, `<`, `>=`, `<=`.
* **Logique** : `AND`, `OR`, `NOT`.
* **Intervalle** : `BETWEEN a AND b` (inclusif).
* **Ensemble** : `IN ('val1', 'val2', 'val3')`.
* **Recherche textuelle** : `LIKE`
  * `%` : n'importe quelle séquence de 0, 1 ou plusieurs caractères.
  * `_` : exactement **un** caractère quelconque.
* **Gestion des valeurs nulles** : `IS NULL` ou `IS NOT NULL` (⚠️ Ne jamais écrire `= NULL`, car en SQL, `NULL = NULL` vaut `UNKNOWN`).

```sql
-- Employés du département 1 avec un salaire supérieur à 10000
SELECT * FROM employes 
WHERE dept_id = 1 AND salaire > 10000;

-- Salaires compris entre 8000 et 13000
SELECT nom, salaire FROM employes 
WHERE salaire BETWEEN 8000 AND 13000;

-- Noms commençant par la lettre 'O'
SELECT * FROM employes 
WHERE nom LIKE 'O%';

-- Employés n'ayant pas de département affecté (dept_id est NULL)
SELECT * FROM employes 
WHERE dept_id IS NULL;
```

### C. Trier et Limiter (`ORDER BY`, `LIMIT`)
* **`ORDER BY colonne [ASC | DESC]`** : `ASC` (croissant, par défaut), `DESC` (décroissant).
* **`LIMIT n OFFSET m`** : Récupère `n` lignes après avoir sauté `m` lignes (utilisé pour la pagination web).

```sql
-- Top 3 des employés les mieux payés
SELECT nom, prenom, salaire 
FROM employes 
ORDER BY salaire DESC 
LIMIT 3;
```

---

## 6. Fonctions d'Agrégation et Regroupement (`GROUP BY` & `HAVING`)

### A. Fonctions d'Agrégation
Elles calculent une valeur unique à partir d'un ensemble de lignes :
* `COUNT(*)` : Compte le nombre total de lignes (y compris les lignes avec des NULLs).
* `COUNT(colonne)` : Compte le nombre de valeurs **non nulles** dans cette colonne.
* `SUM(colonne)` : Calcule la somme.
* `AVG(colonne)` : Calcule la moyenne (ignore les NULLs).
* `MIN(colonne)` : Valeur minimale.
* `MAX(colonne)` : Valeur maximale.

```sql
SELECT 
    COUNT(*) AS total_employes,
    AVG(salaire) AS salaire_moyen,
    MIN(salaire) AS salaire_min,
    MAX(salaire) AS salaire_max,
    SUM(salaire) AS masse_salariale
FROM employes;
```

### B. Regrouper avec `GROUP BY`
`GROUP BY` découpe la table en sous-groupes selon les valeurs d'une ou plusieurs colonnes, puis applique les fonctions d'agrégation à chaque groupe.

```sql
-- Nombre d'employés et salaire moyen par département
SELECT dept_id, COUNT(*) AS nb_employes, AVG(salaire) AS moyenne
FROM employes 
GROUP BY dept_id;
```

### C. La Différence Cruciale : `WHERE` vs `HAVING`
C'est la question favorite de tous les concours d'informatique :
* **`WHERE`** : Filtre les **lignes individuelles** **AVANT** le regroupement. Il ne peut **PAS** utiliser de fonction d'agrégation (ex: `WHERE AVG(salaire) > 5000` est une **erreur de syntaxe**).
* **`HAVING`** : Filtre les **groupes** **APRÈS** le calcul des agrégations du `GROUP BY`.

```sql
-- Départements ayant au moins 2 employés et dont le salaire moyen dépasse 10000
SELECT dept_id, COUNT(*) AS effectif, AVG(salaire) AS salaire_moyen
FROM employes 
WHERE date_embauche >= '2020-01-01'  -- WHERE filtre les lignes d'abord
GROUP BY dept_id                     -- GROUP BY regroupe par département
HAVING COUNT(*) >= 2 AND AVG(salaire) > 10000; -- HAVING filtre les groupes calculés
```

---

## 7. Les Jointures SQL (Maîtriser les Relations)

Dans une base relationnelle, les données sont réparties dans plusieurs tables pour éviter la redondance (normalisation). Les **jointures (`JOIN`)** permettent de recombiner ces tables lors d'une requête.

### Schéma Comparatif des Jointures

```
     Table A              Table B
   ┌─────────┐          ┌─────────┐
   │ 1  Rida │          │ 1  Info │
   │ 2  Sara │          │ 2  RH   │
   │ 3  Omar │          │ 4  Com  │
   └─────────┘          └─────────┘

 1. INNER JOIN (A ∩ B) : Uniquement les correspondances
 ┌─────────┬─────────┐
 │ 1  Rida │ 1  Info │
 │ 2  Sara │ 2  RH   │
 └─────────┴─────────┘

 2. LEFT JOIN (A + correspondances B) : Tout A, NULL si pas de B
 ┌─────────┬─────────┐
 │ 1  Rida │ 1  Info │
 │ 2  Sara │ 2  RH   │
 │ 3  Omar │ NULL    │  <-- Omar apparaît même sans département !
 └─────────┴─────────┘

 3. RIGHT JOIN (B + correspondances A) : Tout B, NULL si pas de A
 ┌─────────┬─────────┐
 │ 1  Rida │ 1  Info │
 │ 2  Sara │ 2  RH   │
 │ NULL    │ 4  Com  │  <-- Le dept 'Com' apparaît même sans employé !
 └─────────┴─────────┘

 4. FULL OUTER JOIN (A ∪ B) : Tout A et tout B
```

### A. `INNER JOIN` (Jointure Interne)
Ne conserve que les lignes qui ont une correspondance dans les deux tables.
```sql
SELECT e.nom, e.prenom, d.nom AS departement, d.lieu
FROM employes e
INNER JOIN departements d ON e.dept_id = d.id;
```

### B. `LEFT JOIN` (ou `LEFT OUTER JOIN`)
Renvoie **toutes les lignes de la table de gauche** (ici `employes`), même si aucune correspondance n'existe dans la table de droite. Les colonnes de droite seront alors remplies avec `NULL`.
```sql
-- Affiche tous les employés, y compris ceux qui n'ont pas de département
SELECT e.nom, e.prenom, d.nom AS departement
FROM employes e
LEFT JOIN departements d ON e.dept_id = d.id;
```

> **Astuce de détection** : Pour trouver les employés sans département :
> ```sql
> SELECT e.nom FROM employes e
> LEFT JOIN departements d ON e.dept_id = d.id
> WHERE d.id IS NULL;
> ```

### C. `RIGHT JOIN` (ou `RIGHT OUTER JOIN`)
Renvoie **toutes les lignes de la table de droite** (ici `departements`), même si aucun employé n'y est rattaché.
```sql
-- Trouver les départements qui n'ont AUCUN employé
SELECT d.nom AS departement_vide
FROM employes e
RIGHT JOIN departements d ON e.dept_id = d.id
WHERE e.id IS NULL;
```

### D. `FULL OUTER JOIN`
Renvoie toutes les lignes dès qu'une correspondance existe à gauche **OU** à droite.
*(En MySQL, on simule le FULL JOIN avec un `UNION` entre un `LEFT JOIN` et un `RIGHT JOIN`).*

### E. `NATURAL JOIN` (Jointure Naturelle)
Relie automatiquement deux tables en se basant sur toutes les colonnes ayant **le même nom** et **le même type** dans les deux tables.
```sql
-- Attention : si les deux tables ont une colonne 'id', il joindra sur 'id' !
SELECT * FROM employes NATURAL JOIN departements;
```

### F. Auto-Jointure (*Self-Join*)
Une table est jointe avec **elle-même** (en utilisant des alias distincts). C'est très utile pour représenter des hiérarchies (ex: un employé et son manager).
```sql
-- Soit une colonne manager_id dans la table employes qui pointe vers employes(id)
SELECT e.nom AS collaborateur, m.nom AS responsable
FROM employes e
LEFT JOIN employes m ON e.manager_id = m.id;
```

---

## 8. Les Sous-Requêtes (*Subqueries*)

Une sous-requête est une requête `SELECT` imbriquée à l'intérieur d'une autre requête SQL.

### A. Sous-requête Scalaire (Renvoie une seule valeur)
```sql
-- Trouver tous les employés qui gagnent plus que le salaire moyen de l'entreprise
SELECT nom, prenom, salaire 
FROM employes 
WHERE salaire > (SELECT AVG(salaire) FROM employes);
```

### B. Sous-requête avec `IN`
```sql
-- Trouver les employés qui travaillent dans les départements situés à 'Rabat'
SELECT nom, prenom 
FROM employes 
WHERE dept_id IN (
    SELECT id FROM departements WHERE lieu = 'Rabat'
);
```

### C. Sous-requête avec `EXISTS` / `NOT EXISTS`
Teste l'existence d'au moins une ligne répondant au critère (très optimisé par les moteurs SGBD) :
```sql
-- Trouver les départements qui comptent au moins un employé
SELECT d.nom 
FROM departements d
WHERE EXISTS (
    SELECT 1 FROM employes e WHERE e.dept_id = d.id
);
```

---

## 9. Transactions et Propriétés ACID

Une **transaction** est une suite d'opérations SQL exécutées comme une **unité de travail indivisible** (Tout ou Rien).
Exemple classique : Un virement bancaire (Débiter le compte A et créditer le compte B).

### Propriétés ACID :
1. **A - Atomicité (*Atomicity*)** : Toutes les opérations de la transaction réussissent, ou aucune n'est appliquée. En cas d'erreur, retour à l'état initial (`ROLLBACK`).
2. **C - Cohérence (*Consistency*)** : La transaction fait passer la base d'un état valide à un autre état valide, en respectant toutes les contraintes d'intégrité.
3. **I - Isolation (*Isolation*)** : Les transactions simultanées ne s'interfèrent pas entre elles.
4. **D - Durabilité (*Durability*)** : Une fois la transaction validée (`COMMIT`), ses modifications sont enregistrées définitivement et survivent même à une panne de courant ou un crash du serveur.

```sql
START TRANSACTION; -- ou BEGIN TRANSACTION

UPDATE comptes SET solde = solde - 1000 WHERE id = 1; -- Débit
UPDATE comptes SET solde = solde + 1000 WHERE id = 2; -- Crédit

-- Si tout est OK :
COMMIT;

-- Si une erreur survient :
-- ROLLBACK;
```
"""

SQL_EXAMPLES = r"""# Cas Pratique Guidé : Système de Gestion d'Entreprise

Pour assimiler parfaitement le DDL, DML, DQL et les jointures, étudions un projet concret de A à Z avec 3 tables en relation :
1. `departements` (id, nom_dept, budget, ville)
2. `employes` (id, nom, prenom, salaire, date_embauche, dept_id)
3. `projets` (id, titre, date_debut, responsable_id)

---

## 1. Création de la Base et des Tables (DDL)

```sql
-- 1. Table des Départements
CREATE TABLE departements (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom_dept VARCHAR(50) NOT NULL UNIQUE,
    budget DECIMAL(12, 2) DEFAULT 100000.00,
    ville VARCHAR(50) NOT NULL
);

-- 2. Table des Employés
CREATE TABLE employes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nom VARCHAR(50) NOT NULL,
    prenom VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    poste VARCHAR(50) NOT NULL,
    salaire DECIMAL(10, 2) NOT NULL CHECK (salaire > 0),
    date_embauche DATE NOT NULL,
    dept_id INT,
    CONSTRAINT fk_emp_dept FOREIGN KEY (dept_id) REFERENCES departements(id) ON DELETE SET NULL
);

-- 3. Table des Projets
CREATE TABLE projets (
    id INT PRIMARY KEY AUTO_INCREMENT,
    titre VARCHAR(100) NOT NULL,
    date_debut DATE NOT NULL,
    responsable_id INT,
    CONSTRAINT fk_projet_resp FOREIGN KEY (responsable_id) REFERENCES employes(id) ON DELETE CASCADE
);
```

---

## 2. Insertion du Jeu de Données Test (DML)

```sql
-- Insertion des Départements
INSERT INTO departements (id, nom_dept, budget, ville) VALUES
(1, 'Informatique', 500000.00, 'Rabat'),
(2, 'Ressources Humaines', 200000.00, 'Casablanca'),
(3, 'Marketing & Vente', 300000.00, 'Tanger'),
(4, 'Recherche & Dév', 450000.00, 'Rabat');

-- Insertion des Employés
INSERT INTO employes (id, nom, prenom, email, poste, salaire, date_embauche, dept_id) VALUES
(101, 'Ouakrim', 'Rida', 'rida@tech.ma', 'Tech Lead', 18000.00, '2020-01-10', 1),
(102, 'Bennani', 'Sara', 'sara@tech.ma', 'Dev Fullstack', 13000.00, '2021-04-15', 1),
(103, 'El Amrani', 'Yassine', 'yassine@tech.ma', 'RH Manager', 11000.00, '2019-11-01', 2),
(104, 'Chraibi', 'Kenza', 'kenza@tech.ma', 'Marketing Lead', 12500.00, '2022-02-20', 3),
(105, 'Tahiri', 'Omar', 'omar@tech.ma', 'Dev DevOps', 14000.00, '2021-08-01', 1),
(106, 'Mansouri', 'Hajar', 'hajar@tech.ma', 'Consultante', 9500.00, '2023-05-12', NULL); -- Sans département

-- Insertion des Projets
INSERT INTO projets (titre, date_debut, responsable_id) VALUES
('Plateforme E-learning Info-Réussite', '2023-01-01', 101),
('Migration Cloud GCP', '2023-06-15', 105),
('Campagne Recrutement 2025', '2024-01-10', 103);
```

---

## 3. Requêtes d'Interrogation et Cas d'Usage Réels (DQL)

### Cas 1 : Trouver la liste complète des employés avec leur nom de département (INNER JOIN)
```sql
SELECT 
    e.id AS matricule,
    CONCAT(e.prenom, ' ', e.nom) AS nom_complet,
    e.poste,
    e.salaire,
    d.nom_dept AS departement,
    d.ville
FROM employes e
INNER JOIN departements d ON e.dept_id = d.id
ORDER BY e.salaire DESC;
```
*Résultat attendu : 5 lignes (Mansouri Hajar n'apparaît pas car son `dept_id` est `NULL`).*

---

### Cas 2 : Afficher TOUS les employés, même ceux sans département (LEFT JOIN)
```sql
SELECT 
    e.nom,
    e.prenom,
    COALESCE(d.nom_dept, 'Non affecté') AS departement
FROM employes e
LEFT JOIN departements d ON e.dept_id = d.id;
```
*Résultat attendu : 6 lignes. Mansouri Hajar apparaît avec la mention `'Non affecté'`.*

---

### Cas 3 : Identifier les départements orphelins (qui n'ont aucun employé) (RIGHT JOIN)
```sql
SELECT 
    d.nom_dept,
    d.ville,
    d.budget
FROM employes e
RIGHT JOIN departements d ON e.dept_id = d.id
WHERE e.id IS NULL;
```
*Résultat attendu : Le département `Recherche & Dév` (id=4) car aucun employé n'y est assigné.*

---

### Cas 4 : Calculer la masse salariale et la moyenne par département avec filtre sur groupe (GROUP BY + HAVING)
```sql
SELECT 
    d.nom_dept,
    COUNT(e.id) AS effectif,
    SUM(e.salaire) AS masse_salariale,
    ROUND(AVG(e.salaire), 2) AS salaire_moyen
FROM departements d
INNER JOIN employes e ON d.id = e.dept_id
GROUP BY d.id, d.nom_dept
HAVING COUNT(e.id) >= 2; -- Ne garder que les départements avec au moins 2 collaborateurs
```
*Résultat : Uniquement le département 'Informatique' (3 employés).*

---

### Cas 5 : Sous-requête - Quels employés gagnent strictement plus que la moyenne générale ?
```sql
SELECT nom, prenom, poste, salaire
FROM employes
WHERE salaire > (
    SELECT AVG(salaire) FROM employes
)
ORDER BY salaire DESC;
```

---

### Cas 6 : Double Jointure - Titre du projet, nom du responsable et ville du département
```sql
SELECT 
    p.titre AS nom_projet,
    p.date_debut,
    CONCAT(e.prenom, ' ', e.nom) AS nom_responsable,
    d.nom_dept,
    d.ville
FROM projets p
INNER JOIN employes e ON p.responsable_id = e.id
LEFT JOIN departements d ON e.dept_id = d.id;
```
"""

SQL_ASTUCES = r"""# 💡 Astuces Concours & Pièges Fréquents en SQL

### 1. L'Ordre Réel d'Exécution d'une Requête SQL
Dans un QCM de concours, on teste souvent si vous comprenez comment le moteur SQL résout la requête. L'ordre d'écriture n'est **PAS** l'ordre d'exécution !

```
 Ordre d'Écriture               Ordre d'Exécution par le Moteur
 1. SELECT                      1. FROM & JOIN (Charge et combine les tables)
 2. FROM                        2. WHERE (Filtre les lignes brutes)
 3. WHERE                       3. GROUP BY (Forme les sous-groupes)
 4. GROUP BY                    4. HAVING (Filtre les groupes calculés)
 5. HAVING                      5. SELECT (Calcule les colonnes et expressions)
 6. ORDER BY                    6. DISTINCT (Élimine les doublons de sortie)
 7. LIMIT                       7. ORDER BY (Trie le résultat final)
                                8. LIMIT / OFFSET (Extrait la tranche demandée)
```
> **Conséquence directe** : Vous ne pouvez **pas** utiliser un alias défini dans le `SELECT` au niveau de la clause `WHERE`, car le `WHERE` s'exécute **avant** le `SELECT` !

---

### 2. Le Piège du `NULL` : Pourquoi `col = NULL` échoue toujours
* En SQL standard, `NULL` ne représente pas la valeur zéro ou une chaîne vide, mais **l'absence totale de valeur** (inconnu).
* Toute comparaison arithmétique avec `NULL` renvoie `UNKNOWN` (considéré comme faux dans un `WHERE`).
* ❌ **Faux** : `WHERE dept_id = NULL` *(ne renverra jamais aucune ligne)*
* ✅ **Vrai** : `WHERE dept_id IS NULL` ou `WHERE dept_id IS NOT NULL`

---

### 3. `COUNT(*)` vs `COUNT(colonne)`
* **`COUNT(*)`** compte **toutes les lignes** répondant au filtre, même si elles ne contiennent que des valeurs `NULL`.
* **`COUNT(colonne)`** compte uniquement les lignes où `colonne` est **non NULL**.
* Si une table `Clients` compte 10 lignes dont 2 ont un `email` à `NULL` :
  * `COUNT(*)` vaut **10**.
  * `COUNT(email)` vaut **8**.

---

### 4. `WHERE` vs `HAVING` : La règle d'or
* Si la condition porte sur une colonne existante sans calcul d'agrégat : **`WHERE`**.
* Si la condition porte sur un résultat de fonction d'agrégation (`SUM`, `COUNT`, `AVG`, `MAX`, `MIN`) : **`HAVING`**.
* ❌ `SELECT dept_id FROM employes WHERE COUNT(*) > 5 GROUP BY dept_id;` (Erreur de syntaxe).
* ✅ `SELECT dept_id FROM employes GROUP BY dept_id HAVING COUNT(*) > 5;`.

---

### 5. `DELETE` vs `TRUNCATE` vs `DROP`
| Critère | `DELETE` | `TRUNCATE` | `DROP` |
| :--- | :--- | :--- | :--- |
| **Famille** | DML | DDL | DDL |
| **Vitesse** | Lente (ligne par ligne avec log) | Très rapide (désalloue les pages) | Instantanée |
| **Condition `WHERE`** | Oui, filtrage possible | Non, vide toute la table | Non |
| **Auto-incrément** | Non réinitialisé | Réinitialisé à 1 | Détruit avec la table |
| **Structure de la table**| Préservée | Préservée | Détruite |

---

### 6. Guide Décisionnel pour Choisir la Bonne Jointure
* **Vous voulez uniquement les éléments qui matchent des deux côtés ?** $\rightarrow$ **`INNER JOIN`**.
* **Vous voulez la liste de gauche complète, même sans correspondance ?** (ex: *Tous les clients, qu'ils aient commandé ou non*) $\rightarrow$ **`LEFT JOIN`**.
* **Vous cherchez les lignes sans correspondance ?** (ex: *Clients sans aucune commande*) $\rightarrow$ **`LEFT JOIN ... WHERE commandes.id IS NULL`**.
* **Vous associez deux tables sur les colonnes de même nom et même type ?** $\rightarrow$ **`NATURAL JOIN`**.
"""

def enrich_course_sql(apps, schema_editor):
    Course = apps.get_model('syllabus', 'Course')
    
    # Target Course pk 2
    Course.objects.filter(pk=2).update(
        content=SQL_CONTENT,
        content_fr=SQL_CONTENT,
        examples=SQL_EXAMPLES,
        examples_fr=SQL_EXAMPLES,
        astuces=SQL_ASTUCES,
        astuces_fr=SQL_ASTUCES
    )

def reverse_enrich_sql(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0006_enrich_web_courses_php_frontend'),
    ]

    operations = [
        migrations.RunPython(enrich_course_sql, reverse_code=reverse_enrich_sql),
    ]
