# Generated by Django on 2026-10-06

from django.db import migrations

def set_sql_video_url(apps, schema_editor):
    Course = apps.get_model('syllabus', 'Course')
    
    # Set video_url on Course 2 (SQL & Relational Databases)
    Course.objects.filter(pk=2).update(
        video_url="https://drive.google.com/file/d/15I6q8nN9IbmefA98dNIPxPiSbthlF8RG/view?usp=sharing"
    )

def reverse_sql_video_url(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0007_enrich_sql_relational_database_course'),
    ]

    operations = [
        migrations.RunPython(set_sql_video_url, reverse_code=reverse_sql_video_url),
    ]
