# Generated by Django on 2026-10-07

from django.db import migrations

UML_CONTENT = r"""# Modélisation UML : Cas d'Utilisation, Classes et Séquences

Bienvenue dans ce guide complet de **Modélisation Orientée Objet avec UML (Unified Modeling Language)**. Conçu spécifiquement pour les candidats préparant les concours d'enseignement (CRMEF, Agrégation) ainsi que les concours d'ingénieurs et techniciens d'État, ce cours allie **rigueur académique**, **illustrations visuelles** et **méthodologie pratique**.

---

## 1. Fondamentaux et Vue d'Ensemble d'UML

### A. Qu'est-ce qu'UML ?
* **UML (Unified Modeling Language)** est un **langage graphique de modélisation standardisé** (normalisé par l'OMG - *Object Management Group*).
* ⚠️ **Piège classique des concours (QCM) :** UML est un **LANGAGE de modélisation**, ce n'est **PAS une méthode**. 
  * Une méthode impose un cycle de vie, des étapes et une démarche de gestion (ex : Merise, 2TUP, RUP, Scrum).
  * UML fournit uniquement la **syntaxe et la sémantique visuelle** (la notation) pour modéliser le système.

### B. Classification des 14 Diagrammes UML 2.5
UML 2.5 structure les modèles en deux grandes familles de diagrammes :
1. **Diagrammes Structurels (Vue Statique) :**
   * Ils décrivent l'architecture statique du système (ce qui existe, les entités et leurs liens permanents).
   * Principaux diagrammes : **Diagramme de Classes**, Diagramme d'Objets, Diagramme de Composants, Diagramme de Déploiement, Diagramme de Paquetages.
2. **Diagrammes Comportementaux (Vue Dynamique) :**
   * Ils décrivent le fonctionnement, les interactions temporelles et l'évolution dans le temps.
   * Principaux diagrammes : **Diagramme de Cas d'Utilisation**, **Diagramme de Séquence**, Diagramme d'Activité, Diagramme d'États-Transitions, Diagramme de Communication.

> **Le Triumvirat des Concours :** Dans plus de 90% des épreuves écrites et QCM, les trois diagrammes demandés sont :
> 1. **Le Diagramme de Cas d'Utilisation** (Besoins fonctionnels externes).
> 2. **Le Diagramme de Classes** (Structure conceptuelle et logicielle).
> 3. **Le Diagramme de Séquence** (Cinématique et chronologie des échanges).

---

## 2. Diagramme de Cas d'Utilisation (Use Case Diagram)

### A. Objectif
Le diagramme de cas d'utilisation sert à formaliser et délimiter les **exigences fonctionnelles** du système. Il répond à la question : **« Que doit faire le système pour satisfaire ses utilisateurs ? »**, sans jamais se soucier des détails techniques internes d'implémentation (boîte noire).

### B. Les Éléments Graphiques
1. **Acteur (Actor) :**
   * Représenté graphiquement par un petit bonhomme (*stick man*) ou un rectangle étiqueté `<<actor>>`.
   * **Définition stricte :** Rôle joué par une entité externe qui interagit directement avec le système.
   * Types d'acteurs :
     * **Acteur Primaire / Principal :** Celui pour qui le cas d'utilisation est conçu et qui déclenche le processus (ex : *Client*).
     * **Acteur Secondaire :** Sollicité par le système pour accomplir le cas d'utilisation (ex : *Serveur Bancaire externe*, *Passerelle SMS*).
2. **Cas d'Utilisation (Use Case) :**
   * Représenté par une **ellipse** contenant un libellé textuel.
   * Règle de nommage : Toujours un **verbe d'action à l'infinitif** suivi d'un complément d'objet (ex : *Retirer de l'argent*, *Consulter le solde*, *Éditer un relevé*).
3. **Frontière du Système (System Boundary) :**
   * Grand rectangle englobant tous les cas d'utilisation. Les acteurs se placent **à l'extérieur** de ce cadre.

---

### C. Les Relations entre Cas d'Utilisation (Cœur des Concours)

![Diagramme de Cas d'Utilisation - Système Bancaire](/images/uml_use_case.png)

#### 1. L'Inclusion : `<<include>>`
* **Définition :** Le cas de base **dépend obligatoirement** du cas inclus. Lors de l'exécution du cas source, le cas inclus est **systématiquement et inconditionnellement** exécuté.
* **Orientation de la flèche :** Trait en pointillés avec flèche ouverte qui **POINTE VERS LE CAS INCLUS** (`Source --<<include>>--> Cible`).
* **Exemple concret :** Pour *Retirer de l'argent*, le système doit impérativement *S'authentifier*. L'authentification est incluse dans le retrait.

#### 2. L'Extension : `<<extend>>`
* **Définition :** Le cas étendu s'ajoute au cas de base de manière **optionnelle, exceptionnelle ou conditionnelle** (soumis à un point d'extension). Le cas de base peut s'exécuter entièrement sans que l'extension ne soit déclenchée.
* **Orientation de la flèche (ATTENTION PIÈGE MAJEUR !) :** La flèche en pointillés **POINTE VERS LE CAS DE BASE** (`Extension --<<extend>>--> Cas de Base`).
* **Exemple concret :** *Imprimer un reçu* ou *Recevoir une alerte SMS* étend *Retirer de l'argent*. Le retrait peut réussir sans impression de ticket.

#### 3. La Généralisation / Spécialisation
* **Entre Acteurs :** Un acteur fils hérite des droits et des cas d'utilisation de l'acteur parent (ex : *Directeur d'agence* hérite de *Conseiller bancaire*).
* **Entre Cas d'Utilisation :** Le cas fils spécialise la manière de réaliser le cas père (ex : *Payer par Carte Bancaire* et *Payer par Virement* spécialisent *Effectuer Paiement*).

---

## 3. Diagramme de Classes (Class Diagram)

### A. Rôle
Le diagramme de classes est le diagramme central de la modélisation objet. Il définit la **structure statique** des données du système en présentant les classes, leurs champs internes, leurs comportements ainsi que les liens logiques qui les unissent.

![Diagramme de Classes UML](/images/uml_class.png)

### B. Anatomie d'une Classe UML
Une classe est représentée par un rectangle divisé en **3 compartiments horizontaux** :
1. **Compartiment Supérieur :** Nom de la classe (centré, en gras, Première lettre majuscule).
2. **Compartiment Central :** Liste des **Attributs**.
3. **Compartiment Inférieur :** Liste des **Opérations / Méthodes**.

#### Visibilité des Membres :
| Symbole | Visibilité | Portée et Signification |
| :---: | :--- | :--- |
| **`+`** | **Public** | Accessible par n'importe quelle classe externe. |
| **`-`** | **Private** | Accessible **uniquement** à l'intérieur de la classe elle-même (Encapsulation). |
| **`#`** | **Protected** | Accessible par la classe et ses **classes filles (sous-classes)**. |
| **`~`** | **Package** | Accessible par toutes les classes situées dans le même paquetage. |

#### Syntaxe formelle :
* Attribut : `visibilité nomAttribut : TypeDonnée [multiplicité] = valeurInitiale`
  * Exemple : `- solde : double = 0.0`
* Méthode : `visibilité nomMethode(param1 : Type, param2 : Type) : TypeRetour`
  * Exemple : `+ retirer(montant : double) : boolean`

---

### C. Les Relations entre Classes : Synthèse et Décryptage

![Guide de Référence UML : Relations et Symboles](/images/uml_relations_summary.png)

#### 1. L'Association Simple
* Trait continu reliant deux classes. Elle indique que les instances des deux classes peuvent échanger des données.
* **Multiplicités (Cardinalités UML) :** Indiquent combien d'instances de la classe B peuvent être associées à une instance de la classe A.
  * `1` : Exactement une instance.
  * `0..1` : Zéro ou une instance (optionnel).
  * `*` ou `0..*` : De zéro à plusieurs instances.
  * `1..*` : Au moins une instance (une ou plusieurs).
  * `n..m` : Entre n et m instances.

#### 2. L'Agrégation (Agrégation Faible)
* **Symbole :** Trait avec un **losange blanc / creux (`◇`)** placé du côté de la classe conteneur (le "Tout").
* **Sémantique :** Relation "Conteneur - Composant" où le cycle de vie du composant est **indépendant** du conteneur. Si le conteneur est détruit, les composants continuent d'exister.
* **Exemple :** Une `Université` et ses `Professeurs`, ou une `Agence` et ses `Employes`. Si l'agence ferme, les employés existent toujours en tant que personnes.

#### 3. La Composition (Agrégation Forte)
* **Symbole :** Trait avec un **losange noir / plein (`◆`)** placé du côté de la classe composite (le "Tout").
* **Sémantique :** Relation d'appartenance forte et exclusive. Les composants ont une **dépendance existentielle** totale envers le composite. Si le composite est détruit, ses composants sont immédiatement détruits.
* **Règle stricte :** La multiplicité du côté composite est **toujours au maximum 1 (`0..1` ou `1`)**.
* **Exemple :** Une `Banque` et ses `Agences`, ou un `Document` et ses `Pages`, ou une `Facture` et ses `LignesFacture`.

#### 4. La Généralisation / Héritage
* **Symbole :** Trait plein se terminant par une **flèche à triangle vide (`▷`)** pointant vers la classe mère (super-classe).
* **Sémantique :** Relation « est un » (*is-a*). La sous-classe hérite de tous les attributs et méthodes de la classe mère, et peut en ajouter de nouveaux ou redéfinir des méthodes existantes (*polymorphisme*).

#### 5. La Dépendance
* **Symbole :** Flèche en pointillés (`- - - >`).
* **Sémantique :** Une classe utilise les services d'une autre de manière éphémère (ex : passage en paramètre d'une méthode ou instanciation locale temporaire).

---

## 4. Diagramme de Séquence (Sequence Diagram)

### A. Rôle
Le diagramme de séquence est un diagramme d'interaction comportemental qui modélise le **déroulement chronologique** des échanges de messages entre un ensemble d'objets ou d'acteurs pour réaliser un cas d'utilisation précis.

![Diagramme de Séquence UML](/images/uml_sequence.png)

### B. Éléments Graphiques
1. **Ligne de Vie (Lifeline) :**
   * Rectangle placé au sommet représentant l'objet, sous la syntaxe `nomObjet : NomClasse` ou simplement `:NomClasse` (instance anonyme), prolongé vers le bas par une ligne pointillée verticale matérialisant l'axe du temps (le temps s'écoule de haut en bas).
2. **Période d'Activité (Barre d'activation) :**
   * Rectangle étroit vertical posé sur la ligne de vie, signalant que l'objet a le contrôle et exécute une méthode.
3. **Types de Messages :**
   * **Message Synchrone (Flèche pleine `──▶`) :** L'émetteur appelle une méthode et attend la fin de son exécution pour continuer.
   * **Message Asynchrone (Flèche ouverte `──>`) :** L'émetteur envoie une information (ou un signal) et poursuit son traitement sans attendre.
   * **Message de Retour (Flèche pointillée `< - - -`) :** Renvoi du résultat d'une fonction vers l'appelant.
   * **Message Réflexif (Self-Message) :** Flèche qui boucle sur la même ligne de vie vers le bas pour représenter un appel interne (`this.calculerInterets()`).

### C. Fragments Combinés (Contrôle de Flux en UML 2)
UML 2 a introduit des cadres structurés pour représenter les logiques algorithmiques :
* **`alt` (Alternatives) :** Équivalent de l'instruction conditionnelle `if ... else`. Divisé en compartiments horizontaux par des traits tiretés, chaque compartiment portant une condition de garde entre crochets `[condition]`.
* **`opt` (Optionnel) :** Équivalent d'un `if` sans `else`. S'exécute uniquement si la garde `[condition]` est vraie.
* **`loop` (Boucle) :** Équivalent de `while` ou `for`. Répète les interactions tant que la condition `loop [min, max]` ou `loop [i < n]` est satisfaite.
* **`par` (Parallèle) :** Exécution concurrente de deux blocs de messages.
"""

UML_EXAMPLES = r"""# Études de Cas Pratiques Corrigées (Spécial Concours)

Voici deux études de cas complètes, résolues pas à pas, représentatives des épreuves écrites des concours marocains (CRMEF Informatique, Concours des Ingénieurs et Administrateurs d'État).

---

## Exercice 1 : Modélisation des Cas d'Utilisation — « Gestion de Borne Bancaire (DAB) »

### 1. Énoncé du Problème
Un établissement bancaire souhaite concevoir le logiciel d'une borne de distribution automatique de billets (DAB).
* Un **Client** muni de sa carte bancaire peut **Consulter son solde**, **Effectuer un virement** ou **Retirer des espèces**.
* Pour toute opération financière, le client doit **obligatoirement s'authentifier** en composant son code PIN à 4 chiffres.
* Lors d'un retrait, le client a la possibilité, s'il le souhaite, de **demander l'impression d'un ticket récapitulatif**.
* Si le solde du compte est insuffisant, le système déclenche une **alerte solde insuffisant**.
* Un **Agent de maintenance** peut **Recharger les billets** ou **Consulter le journal technique d'audit**.

---

### 2. Solution et Démarche Méthodologique

#### Étape 1 : Recensement des Acteurs
* **Client** (Acteur principal humain).
* **Agent de Maintenance** (Acteur principal humain pour les fonctions techniques).
* **Serveur du Système d'Information Bancaire** (Acteur secondaire système, validant le code PIN et le solde).

#### Étape 2 : Identification des Relations `<<include>>` et `<<extend>>`
* Les cas *Consulter Solde*, *Effectuer Virement* et *Retirer Espèces* partagent une étape obligatoire et incontournable : **S'authentifier**.
  * $\rightarrow$ **Relation `<<include>>`** : `Retirer Espèces --<<include>>--> S'authentifier`.
* L'impression du reçu est optionnelle et choisie par l'utilisateur :
  * $\rightarrow$ **Relation `<<extend>>`** : `Imprimer Reçu --<<extend>>--> Retirer Espèces` *(avec la flèche orientée vers Retirer Espèces)*.
* L'alerte solde insuffisant est un comportement conditionnel d'erreur :
  * $\rightarrow$ **Relation `<<extend>>`** : `Alerter Solde Insuffisant --<<extend>>--> Retirer Espèces`.

#### Étape 3 : Fiche Descriptive Textuelle Normalisée (Très Demandée aux Écrits)
```
Cas d'Utilisation : Retirer Espèces
Acteur Principal   : Client
Acteur Secondaire  : Serveur Bancaire
Préconditions      : La carte bancaire est insérée dans la borne ; Le DAB dispose de billets.
Postconditions     : Les billets sont distribués ; Le solde du compte est débité.

Scénario Nominal (Succès) :
  1. Le client sélectionne l'option "Retrait d'espèces".
  2. Le système exécute le cas inclus "S'authentifier" (saisie du code PIN).
  3. Le système demande le montant souhaité.
  4. Le client choisit le montant.
  5. Le système interroge le Serveur Bancaire pour vérifier le plafond et le solde.
  6. Le système distribue les billets et éjecte la carte bancaire.
  7. Le client récupère sa carte et ses billets.

Scénarios Alternatifs / Extensions :
  4a. Point d'extension [Demande de ticket] :
      4a.1. Le système exécute le cas d'extension "Imprimer Reçu".
  5a. Point d'extension [Solde Insuffisant] :
      5a.1. Le système exécute le cas d'extension "Alerter Solde Insuffisant".
      5a.2. La transaction est annulée, la carte est rendue au client.
```

---

## Exercice 2 : Diagramme de Classes — « Plateforme E-Commerce »

### 1. Énoncé du Problème
Concevez le diagramme de classes d'une boutique en ligne respectant les règles métier suivantes :
* Un **Client** est caractérisé par un identifiant `id`, son `nom`, son `email` et son `motDePasse`.
* Un client peut passer plusieurs **Commandes**, mais une commande appartient à un et un seul client.
* Une commande possède un `numero`, une `dateCommande` et un `statut` (En attente, Payée, Expédiée).
* Une commande est composée d'une ou plusieurs **Lignes de Commande**. Chaque ligne précise la `quantité` commandée et le `prixUnitaire`. Si la commande est supprimée du système, ses lignes de commande associées sont automatiquement détruites.
* Une ligne de commande référence exactement un **Produit** (caractérisé par sa `reference`, sa `designation`, son `prix` et son `stock`). Un produit peut figurer dans plusieurs lignes de commande distinctes.
* Les produits sont classés dans des **Catégories** (`id`, `nomCategorie`). Si une catégorie est supprimée, les produits ne sont pas détruits, ils restent en base de données.
* Le client règle sa commande via un **Paiement** (`idPaiement`, `montant`, `datePaiement`). Le paiement peut être soit un **PaiementCarte** (`numeroCarte`, `dateExpiration`), soit un **PaiementPayPal** (`comptePayPal`).

---

### 2. Modélisation et Justification des Choix

#### A. Analyse des Relations Clés
1. **Client $\longleftrightarrow$ Commande : Association Simple**
   * Multiplicité : `Client (1) ────────── (0..*) Commande`.
   * Un client peut n'avoir encore rien commandé (`0`), ou passer plusieurs commandes (`*`).
2. **Commande $\longleftrightarrow$ LigneCommande : Composition (`◆`)**
   * **Pourquoi la composition ?** Parce qu'une ligne de commande ne peut pas exister dans le vide sans la commande dont elle fait partie. Si l'utilisateur annule et supprime la commande, les lignes disparaissent.
   * Symbole : Losange plein noir côté `Commande`. Multiplicité : `Commande (1) ◆────────── (1..*) LigneCommande`.
3. **Categorie $\longleftrightarrow$ Produit : Agrégation (`◇`)**
   * **Pourquoi l'agrégation ?** Les produits ont une existence propre en stock. Supprimer la catégorie "Promotions d'été" ne détruit pas les ordinateurs ni les téléphones.
   * Symbole : Losange vide blanc côté `Categorie`. Multiplicité : `Categorie (0..1) ◇────────── (0..*) Produit`.
4. **PaiementCarte / PaiementPayPal $\longleftrightarrow$ Paiement : Héritage (`▷`)**
   * `Paiement` est une classe abstraite mère. Les classes filles `PaiementCarte` et `PaiementPayPal` héritent de ses attributs et méthodes avec un triangle vide pointant vers `Paiement`.

#### B. Représentation Textuelle du Modèle de Classes
```
┌─────────────────────────────────┐
│             Client              │
├─────────────────────────────────┤
│ - id : int                      │
│ - nom : String                  │
│ - email : String                │
├─────────────────────────────────┤
│ + passerCommande() : Commande   │
└─────────────────────────────────┘
                 │ 1
                 │
                 │ 0..*
┌─────────────────────────────────┐                 ┌───────────────────────────────┐
│            Commande             │  1         1..* │         LigneCommande         │
├─────────────────────────────────┤◆───────────────├───────────────────────────────┤
│ - numero : String               │                 │ - quantite : int              │
│ - dateCommande : Date           │                 │ - prixUnitaire : double       │
│ - statut : String               │                 ├───────────────────────────────┤
├─────────────────────────────────┤                 │ + sousTotal() : double        │
│ + calculerTotal() : double      │                 └───────────────────────────────┘
└─────────────────────────────────┘                                 │ *
                 │ 1                                                │
                 │                                                  │ 1
                 │ 1                               ┌───────────────────────────────┐
┌─────────────────────────────────┐                │            Produit            │
│       Paiement {abstract}       │                ├───────────────────────────────┤
├─────────────────────────────────┤                │ - reference : String          │
│ - idPaiement : String           │                │ - designation : String        │
│ - montant : double              │                │ - prix : double               │
│ - datePaiement : Date           │                │ - stock : int                 │
├─────────────────────────────────┤                ├───────────────────────────────┤
│ + valider() : boolean           │                │ + verifierStock() : boolean   │
└─────────────────────────────────┘                └───────────────────────────────┘
              ▲      ▲                                              ▲
             ┌┘      └┐                                             │ 0..*
            ┌┴┐      ┌┴┐                                            │
   ┌──────────┐      ┌──────────┐                  ┌───────────────────────────────┐
   │PaiementCB│      │PaiementPP│                  │           Categorie           │
   └──────────┘      └──────────┘                  ├───────────────────────────────┤
                                                   │ - id : int                    │
                                                   │ - nomCategorie : String       │
                                                   ├───────────────────────────────┤
                                                   └───────────────────────────────┘
                                                                    ◇ (Agrégation)
```

#### C. Traduction en Code Orienté Objet (Exemple en Java / C#)
```java
// Exemple d'implémentation de la Composition :
public class Commande {
    private String numero;
    private List<LigneCommande> lignes; // Cycle de vie lié

    public Commande(String numero) {
        this.numero = numero;
        this.lignes = new ArrayList<>();
    }

    public void ajouterLigne(Produit p, int quantite) {
        // La Commande crée et encapsule directement ses lignes
        this.lignes.add(new LigneCommande(quantite, p.getPrix(), p));
    }

    public double calculerTotal() {
        return lignes.stream().mapToDouble(LigneCommande::sousTotal).sum();
    }
}
```

---

## Exercice 3 : Diagramme de Séquence — « Validation de Paiement par Carte avec Code OTP »

### Scénario :
1. L'acteur **Client** clique sur "Payer la commande" sur l'**Interface Web**.
2. L'**Interface Web** transmet la requête de débit avec les informations bancaires au **Contrôleur de Commande**.
3. Le **Contrôleur** invoque la méthode synchrone `autoriserPaiement(montant)` sur la **Passerelle Bancaire Externe**.
4. La **Passerelle Bancaire** envoie un SMS contenant un code OTP au **Serveur SMS**, qui le délivre au Client.
5. Le Client saisit le code reçu sur l'Interface Web.
6. Le Contrôleur transmet `validerOTP(code)` à la Passerelle.
7. **Alternative `alt` :**
   * **[Code OTP Valide et Solde Suffisant]** :
     * La passerelle retourne `PaiementAccepté`.
     * Le contrôleur met à jour le statut de la `Commande` à "PAYÉE".
     * L'interface affiche l'écran de confirmation au Client.
   * **[Code Invalide ou Solde Insuffisant]** :
     * La passerelle renvoie `ErreurPaiement`.
     * L'interface affiche le message d'échec et invite le client à réitérer l'opération.
"""

UML_ASTUCES = r"""# Astuces d'Examen, Pièges Fréquents et Questions Corrigées

Cette section récapitule les subtilités indispensables pour obtenir la note maximale aux questions d'analyse et de modélisation UML.

---

## 1. Le Top 7 des Pièges Classiques en Concours

| N° | Piège Fréquent | Règle d'Or à Retenir |
| :---: | :--- | :--- |
| **1** | **Confondre UML et Merise / Agile** | UML est un **langage** de modélisation, pas une méthode de développement ni un processus. |
| **2** | **Le sens de la flèche `<<extend>>`** | 🚨 **La flèche pointe vers le cas de base**, JAMAIS vers l'extension ! Retenez : *l'extension prend appui sur le cas de base*. |
| **3** | **Obligatoire vs Optionnel** | `<<include>>` = obligatoire et systématique. `<<extend>>` = optionnel et conditionnel. |
| **4** | **Composition vs Agrégation** | Composition = losange **plein noir (◆)**, cycle de vie fusionné, multiplicité max 1 côté conteneur. Agrégation = losange **vide (◇)**, objets indépendants. |
| **5** | **Multiplicité UML vs Merise** | En Merise, la cardinalité `(0,n)` se lit sur l'entité de départ vers l'association. En UML, la multiplicité `0..*` s'écrit **au bout du trait**, juste à côté de la classe cible ! |
| **6** | **Objets dans les diagrammes de séquence** | La ligne de vie représente une **instance (objet)** et non une classe ! On écrit `:Client` ou `c:Client` (souligné). |
| **7** | **Classe Abstraite** | En UML, le nom d'une classe abstraite s'écrit en *italique* ou s'accompagne de la mention `{abstract}`. Une classe abstraite ne peut jamais être instanciée directement. |

---

## 2. Tableau Mémo-Technique Éclair

```
  SYMBOLE                   SIGNIFICATION                       EXEMPLE CONCRET
 ─────────                 ───────────────                     ─────────────────
  ───────                   Association simple                  Client ── Voiture
  ◇──────                   Agrégation (Partie libre)           Équipe ◇── Joueur
  ◆──────                   Composition (Partie liée)           Maison ◆── Mur
  ──────▷                   Héritage / Généralisation           Chien ──▷ Animal
  - - - ▷                   Réalisation d'interface            Service ┄┄▷ IService
  - - - >                   Dépendance temporaire               Facture ┄┄> Imprimante
  <<include>>               Étape obligatoire                   Retirer ┄> Authentifier
  <<extend>>                Étape optionnelle                   Alerte ┄> Retirer
```

---

## 3. Cinq Questions Réelles de Concours Décortiquées

### Question 1 (Concours 2025 - Q33)
**Énoncé :** Dans un diagramme de cas d'utilisation, un acteur peut représenter :
* A. Uniquement un utilisateur humain
* B. Uniquement un rôle spécifique
* **C. Un rôle, humain ou système, interagissant avec le système étudié** *(Bonne réponse)*
* D. Un module interne du système
> **Explication du jury :** Un acteur n'est jamais un module interne du logiciel (principe de la boîte noire). Il représente impérativement une entité externe qui interagit avec le système. Il peut s'agir d'un humain (ex : Caissier), d'un équipement matériel (ex : Capteur thermique), ou d'un autre système informatique (ex : Serveur de carte bancaire).

---

### Question 2 (Concours 2025 - Q31)
**Énoncé :** Dans un diagramme de classes UML, une ligne simple reliant deux classes signifie :
* **A. Une association** *(Bonne réponse)*
* B. Une dépendance
* C. Une composition
* D. Une généralisation
> **Explication du jury :** Le trait plein simple sans losange ni triangle correspond à l'association de base. La dépendance utilise des pointillés (`--->`), la composition un losange plein (`◆`), et la généralisation un triangle non rempli (`──▷`).

---

### Question 3 (Concours 2024 - Q54)
**Énoncé :** En UML, que signifie la multiplicité `1..*` ?
* A. Plusieurs incluant la possibilité d'aucun
* B. Exactement 1
* C. Au plus un
* **D. Au moins un** *(Bonne réponse)*
> **Explication du jury :** `1..*` se décompose en : borne inférieure = 1 (au minimum un élément), et borne supérieure = `*` (plusieurs ou une infinité). La signification formelle est donc strictement **« au moins un »**.

---

### Question 4 (Concours 2022 - Q44)
**Énoncé :** En UML, dans un diagramme de séquence, pour qu'un objet puisse envoyer un message à lui-même :
* A. La flèche d'envoi part de l'objet et y revient
* **B. La flèche d'envoi part de l'objet et revient plus bas sur sa ligne de vie** *(Bonne réponse)*
* C. La flèche d'envoi part de l'objet et revient plus haut sur sa ligne de vie
* D. La flèche d'envoi part de la ligne de vie de l'objet et revient sur l'objet
> **Explication du jury :** Le temps s'écoulant toujours de haut en bas sur la ligne de vie, tout message réflexif (*self-message*) part de la barre d'activation et boucle pour se terminer **plus bas** afin de matérialiser la durée de traitement de l'opération interne.

---

### Question 5 (Concours Spécial Enseignement CRMEF)
**Énoncé :** Lors de la modélisation d'un système de gestion de bibliothèque, si un `Livre` est détruit, ses `Exemplaires` physiques n'ont plus de raison d'exister. En revanche, si la `Bibliothèque` ferme, les `Auteurs` des livres existent toujours. Quelles sont les relations appropriées ?
* **Réponse attendue :**
  1. Entre `Livre` et `Exemplaire` : **Composition (`◆`)** car il y a dépendance d'existence absolue.
  2. Entre `Bibliothèque` et `Auteur` (ou `Livre` et `Auteur`) : **Agrégation (`◇`)** ou **Association simple**, car les auteurs existent indépendamment de la bibliothèque.
"""

def enrich_course_uml(apps, schema_editor):
    Course = apps.get_model('syllabus', 'Course')
    
    # Target Course pk 1 (Modélisation UML)
    Course.objects.filter(pk=1).update(
        content=UML_CONTENT,
        content_fr=UML_CONTENT,
        examples=UML_EXAMPLES,
        examples_fr=UML_EXAMPLES,
        astuces=UML_ASTUCES,
        astuces_fr=UML_ASTUCES
    )

def reverse_enrich_uml(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0008_set_sql_course_video_url'),
    ]

    operations = [
        migrations.RunPython(enrich_course_uml, reverse_code=reverse_enrich_uml),
    ]
