# Generated by Django on 2026-10-07

from django.db import migrations

GPI_CONTENT = r"""# Gestion de Projets Informatiques et Cycles de Vie Logiciels

Bienvenue dans ce guide complet de **Gestion de Projets Informatiques (GPI)** et des **Cycles de Vie Logiciels (SDLC)**. Conçu spécifiquement pour les épreuves écrites et QCM des concours d'enseignement (CRMEF, Agrégation) ainsi que des concours d'ingénieurs et administrateurs d'État, ce cours présente la démarche méthodologique indispensable, les outils de planification opérationnelle (**WBS, PERT, Gantt**) et les cadres méthodologiques (**Cascade, Cycle en V, Agile/Scrum, DevOps**).

---

## 1. Fondamentaux de la Gestion de Projet Informatique

### A. Définition et Spécificités d'un Projet IT
Un **projet informatique** est une entreprise temporaire initiée dans le but de produire un résultat, un service ou un produit logiciel unique, sous des contraintes strictes de ressources, de calendrier et de qualité.

Les projets informatiques présentent des spécificités qui les rendent complexes :
* **Immatérialité du logiciel :** Visibilité réduite de l'avancement avant les phases de test.
* **Évolution rapide des besoins :** Effet tunnel à éviter absolument.
* **Forte dépendance technologique et humaine :** Compétences pointues requises.

### B. Le Triangle d'Or (Triple Contrainte)
Tout projet est gouverné par trois paramètres interdépendants. Modifier l'un impacte inévitablement les deux autres :
1. **Coût (Budget) :** Ressources financières et humaines allouées.
2. **Délai (Temps) :** Échéance finale et calendrier des livrables.
3. **Périmètre / Qualité (Scope) :** Fonctionnalités attendues et niveau de robustesse technique.

---

## 2. Les Cycles de Vie Logiciels (SDLC - Software Development Life Cycle)

Le cycle de vie définit la succession des étapes franchies par un logiciel depuis l'expression initiale du besoin jusqu'à son retrait de service.

![Cycles de Vie Logiciels : Modèle en V vs Agile Scrum](/images/sdlc_vmodel_agile.png)

### A. Modèle Linéaire et en Cascade (Waterfall)
* **Principe :** Démarche séquentielle stricte où chaque phase (Exigences $\rightarrow$ Conception $\rightarrow$ Codage $\rightarrow$ Tests $\rightarrow$ Déploiement) doit être entièrement validée avant de démarrer la suivante.
* **Avantages :** Structure claire, documentation exhaustive, planification budgétaire simple.
* **Inconvénients majeurs :** Effet tunnel, détection très tardive des erreurs de conception, impossibilité de s'adapter aux changements de besoins du client en cours de route.

### B. Le Modèle en V (Standard des Systèmes Critiques)
Le modèle en V est une amélioration majeure de la cascade, structurée autour du principe de **vérification et validation** :
* **Branche descendante (Conception & Spécification) :**
  1. *Exigences / Analyse des besoins métier*
  2. *Conception générale / Architecture système*
  3. *Conception détaillée / Modélisation des modules*
  4. *Codage (Sommet bas du V)*
* **Branche montante (Validation & Tests) :**
  1. *Tests Unitaires :* Vérifient le codage au niveau des fonctions/classes.
  2. *Tests d'Intégration :* Vérifient les interfaces entre modules (conception détaillée).
  3. *Tests Système :* Vérifient le respect de l'architecture globale.
  4. *Tests d'Acceptation / Recette utilisateur :* Vérifient que le logiciel satisfait les besoins métier initiaux.

### C. Le Modèle en Spirale (Barry Boehm)
* Modèle itératif axé sur l'**évaluation continue des risques**.
* Chaque spire du cycle comprend 4 quadrants : Définition des objectifs $\rightarrow$ Analyse et réduction des risques (prototypage) $\rightarrow$ Développement et tests $\rightarrow$ Planification de la spire suivante.

### D. Les Méthodes Agiles (Scrum & Kanban)
* Fondées sur le **Manifeste Agile (2001)** qui privilégie :
  * *Les individus et leurs interactions* plutôt que les processus et les outils.
  * *Un logiciel opérationnel* plutôt que une documentation exhaustive.
  * *La collaboration avec les clients* plutôt que la négociation contractuelle.
  * *L'adaptation au changement* plutôt que le suivi rigide d'un plan.

#### Le Cadre Scrum :
* **Rôles clés :**
  * **Product Owner (PO) :** Porte la voix du client et la vision métier. Responsable exclusif du *Product Backlog* (priorisation de la valeur).
  * **Scrum Master (SM) :** Facilitateur et garant du respect du cadre Scrum. Élimine les obstacles rencontrés par l'équipe (ce n'est PAS un chef hiérarchique !).
  * **Équipe de Développement :** Pluridisciplinaire, autonome et auto-organisée (3 à 9 personnes).
* **Rituels (Événements) :**
  * *Sprint Planning :* Sélection des éléments du Product Backlog pour le Sprint à venir.
  * *Daily Scrum (15 min) :* Synchronisation quotidienne de l'équipe (Ce que j'ai fait hier, ce que je fais aujourd'hui, les obstacles bloquants).
  * *Sprint Review :* Démonstration de l'incrément opérationnel aux parties prenantes.
  * *Rétrospective :* Amélioration continue des processus et de la dynamique d'équipe.
* **Artéfacts :** *Product Backlog*, *Sprint Backlog*, *Incrément Potentiellement Livrable*.

---

## 3. Les Outils Fondamentaux de Planification : WBS, PERT et GANTT

La planification d'un projet repose sur une démarche en trois temps indissociables :
1. **Décomposer le projet :** Le **WBS** répond à la question : *« Que doit-on produire ? »*.
2. **Ordonnancer logiquement les tâches :** Le **PERT** répond à la question : *« Dans quel ordre logique ? »*.
3. **Planifier dans le temps et affecter les ressources :** Le **GANTT** répond à la question : *« Quand et par qui ? »*.

---

### A. L'Organigramme des Tâches (WBS - Work Breakdown Structure)

Le WBS est la décomposition hiérarchique arborescente de la totalité du travail à réaliser pour accomplir les livrables du projet.

![WBS - Organigramme des Tâches](/images/wbs_hierarchy.png)

#### Règles de construction du WBS :
* **Règle des 100% :** Le WBS doit représenter 100% du travail défini par le périmètre du projet, ni plus, ni moins.
* **Orientation livrables :** Chaque boîte représente un livrable vérifiable et mesurable (produit ou composant), et non une simple action vague.
* **Lot de travail (*Work Package*) :** Niveau le plus bas de la décomposition. Il a une durée estimable, un coût calculable et un responsable unique.

---

### B. Le Réseau PERT (Program Evaluation and Review Technique) & CPM

Le PERT est un outil graphique d'ordonnancement sous forme de graphe fléché modélisant les dépendances logiques entre les tâches du projet.

![Réseau PERT et Chemin Critique](/images/pert_network.png)

#### 1. Représentation Formelle
* **Nœud (Événement / Étape) :** Représente un jalon (instant sans durée).
* **Arc (Flèche) :** Représente une tâche consommatrice de temps et de ressources, annotée de son nom et de sa durée.

#### 2. Démarche de Calcul des Dates et Marges
Pour chaque étape $i$, on calcule deux dates clés :
1. **Date au plus tôt ($ES_i$ - Early Start) :** 
   * Parcours avant (de gauche à droite) :
   * $ES_0 = 0$
   * Pour l'étape $j$ : $ES_j = \max_{(i \rightarrow j)} (ES_i + \text{Durée}(i, j))$
2. **Date au plus tard ($LF_i$ - Latest Finish) :**
   * Parcours arrière (de droite à gauche) :
   * Pour la fin : $LF_{\text{fin}} = ES_{\text{fin}}$
   * Pour l'étape $i$ : $LF_i = \min_{(i \rightarrow j)} (LF_j - \text{Durée}(i, j))$
3. **Marge Totale ($MT$) :**
   * Retard maximal que peut prendre une tâche sans reporter la date d'achèvement finale du projet :
   * $MT = LF_j - ES_i - \text{Durée}(i, j)$
4. **Marge Libre ($ML$) :**
   * Retard maximal qu'une tâche peut prendre sans impacter la date au plus tôt de ses successeurs directs :
   * $ML = \min_{(j \rightarrow k)} (ES_k) - (ES_i + \text{Durée}(i, j))$

#### 3. Le Chemin Critique
* **Définition :** La suite ininterrompue de tâches dont la **marge totale est nulle ($MT = 0$)**.
* **Propriété clé :** C'est le **chemin dont la durée cumulée est la plus longue** à travers le graphe. Tout retard sur une tâche critique retarde d'autant la fin du projet !

---

### C. Le Diagramme de Gantt (Planning Temporel et Calendaire)

Créé par Henry Gantt, le **diagramme de Gantt** est l'outil visuel le plus populaire et le plus utilisé dans la gestion de projet moderne. Il traduit les dépendances logiques du PERT en un **calendrier opérationnel réel**.

![Diagramme de Gantt](/images/gantt_chart.png)

#### 1. Composants d'un Diagramme de Gantt
* **Axe vertical (à gauche) :** Liste des tâches, lots de travail et jalons du projet.
* **Axe horizontal (en haut) :** Échelle de temps calendaire (Jours, Semaines, Mois, Trimestres).
* **Barres horizontales :** Chaque barre représente une tâche. La position de l'extrémité gauche indique la date de début, l'extrémité droite indique la date de fin, et la longueur totale correspond à la durée.
* **Flèches de dépendance :** Relient la fin d'une tâche au début de sa dépendance.
* **Jalons (*Milestones*) :** Représentés par un **losange (`◆`)**. Un jalon indique un événement majeur (ex : *Validation du cahier des charges*, *Mise en production*). Sa durée est **strictement égale à 0 jour**.

#### 2. Types de Liaisons Temporelles entre Tâches
| Type de Liaison | Code | Signification | Exemple |
| :--- | :---: | :--- | :--- |
| **Fin à Début** *(Finish-to-Start)* | **FD / FS** | La tâche B ne peut débuter que lorsque la tâche A est achevée (cas le plus fréquent). | Les tests démarrent après la fin du codage. |
| **Début à Début** *(Start-to-Start)* | **DD / SS** | La tâche B démarre en même temps que la tâche A. | L'enregistrement vidéo démarre en même temps que la diffusion. |
| **Fin à Fin** *(Finish-to-Finish)* | **FF** | La tâche B ne peut se terminer tant que la tâche A n'est pas terminée. | L'inspection de qualité finit quand le montage s'arrête. |
| **Début à Fin** *(Start-to-Finish)* | **DF / SF** | La tâche B ne peut se terminer qu'après le démarrage de la tâche A. | Relève de garde (très rare en informatique). |

#### 3. Comparatif Synthétique : WBS vs PERT vs GANTT
| Critère | WBS (OTP) | Réseau PERT | Diagramme de GANTT |
| :--- | :--- | :--- | :--- |
| **Objectif principal** | Décomposer le périmètre | Ordonnancer et calculer les marges | Planifier dans le temps et affecter les équipes |
| **Question clé** | *Quoi ?* | *Dans quel ordre logique ?* | *Quand et par qui ?* |
| **Gestion du temps** | Aucune notion de durée | Durées logiques relatives (jours) | Calendrier réel absolu (dates, jours fériés) |
| **Chemin critique** | Non visible | **Calculé et mis en évidence** | **Visualisé en couleur distincte** |
| **Ressources** | Attribuées au lot | Non gérées | **Gérées et lissées** |
"""

GPI_EXAMPLES = r"""# Études de Cas Pratiques Corrigées (Spécial Concours)

Voici des exercices complets et corrigés pas à pas, représentatifs des épreuves des concours (CRMEF Informatique et Concours d'Ingénieurs d'État).

---

## Exercice 1 : Étude Complète d'Ordonnancement — Du Tableau d'Antécédence au GANTT

### 1. Énoncé du Problème
Une équipe de développement doit concevoir un portail web éducatif. Voici le tableau des tâches recensées, leurs durées prévisionnelles et leurs dépendances :

| Tâche | Description | Durée (jours) | Prédécesseurs directs |
| :---: | :--- | :---: | :---: |
| **A** | Rédaction du cahier des charges | 5 | Aucun |
| **B** | Conception de la base de données | 4 | A |
| **C** | Maquettage de l'interface utilisateur | 6 | A |
| **D** | Développement de l'API Backend | 8 | B |
| **E** | Développement du Frontend React | 7 | C |
| **F** | Intégration et Tests d'API | 3 | D, E |
| **G** | Recette client et Déploiement | 2 | F |

### 2. Questions Types d'Examen :
1. Construire le tableau complet des dates au plus tôt ($ES, EF$), dates au plus tard ($LS, LF$), marges totales ($MT$) et marges libres ($ML$).
2. Identifier le chemin critique et la durée totale du projet.
3. Représenter textuellement le diagramme de Gantt correspondant.

---

### 3. Solution Détaillée Pas à Pas

#### Étape 1 : Calcul du Passage Avant (Dates au plus tôt)
* $ES(A) = 0 \rightarrow EF(A) = 0 + 5 = 5$.
* $ES(B) = EF(A) = 5 \rightarrow EF(B) = 5 + 4 = 9$.
* $ES(C) = EF(A) = 5 \rightarrow EF(C) = 5 + 6 = 11$.
* $ES(D) = EF(B) = 9 \rightarrow EF(D) = 9 + 8 = 17$.
* $ES(E) = EF(C) = 11 \rightarrow EF(E) = 11 + 7 = 18$.
* Pour $F$, elle dépend de $D$ et $E$ : $ES(F) = \max(EF(D), EF(E)) = \max(17, 18) = 18 \rightarrow EF(F) = 18 + 3 = 21$.
* $ES(G) = EF(F) = 21 \rightarrow EF(G) = 21 + 2 = 23$.

$\rightarrow$ **Durée totale du projet = 23 jours.**

#### Étape 2 : Calcul du Passage Arrière (Dates au plus tard)
On fixe $LF(G) = EF(G) = 23$ jours.
* $LS(G) = 23 - 2 = 21$.
* $LF(F) = LS(G) = 21 \rightarrow LS(F) = 21 - 3 = 18$.
* $LF(E) = LS(F) = 18 \rightarrow LS(E) = 18 - 7 = 11$.
* $LF(D) = LS(F) = 18 \rightarrow LS(D) = 18 - 8 = 10$.
* $LF(C) = LS(E) = 11 \rightarrow LS(C) = 11 - 6 = 5$.
* $LF(B) = LS(D) = 10 \rightarrow LS(B) = 10 - 4 = 6$.
* Pour $A$, elle précède $B$ et $C$ : $LF(A) = \min(LS(B), LS(C)) = \min(6, 5) = 5 \rightarrow LS(A) = 5 - 5 = 0$.

#### Étape 3 : Synthèse des Marges
| Tâche | Durée | ES | EF | LS | LF | Marge Totale ($MT = LF - EF$) | Marge Libre ($ML$) | Critique ? |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| **A** | 5 | 0 | 5 | 0 | 5 | **0** | **0** | **OUI** |
| **B** | 4 | 5 | 9 | 6 | 10 | **1** | **0** ($ES(D) - EF(B) = 9 - 9 = 0$) | NON |
| **C** | 6 | 5 | 11 | 5 | 11 | **0** | **0** | **OUI** |
| **D** | 8 | 9 | 17 | 10 | 18 | **1** | **1** ($ES(F) - EF(D) = 18 - 17 = 1$) | NON |
| **E** | 7 | 11 | 18 | 11 | 18 | **0** | **0** | **OUI** |
| **F** | 3 | 18 | 21 | 18 | 21 | **0** | **0** | **OUI** |
| **G** | 2 | 21 | 23 | 21 | 23 | **0** | **0** | **OUI** |

#### Étape 4 : Détermination du Chemin Critique
Les tâches dont la marge totale est nulle ($MT = 0$) forment le chemin critique :
$$\mathbf{A \longrightarrow C \longrightarrow E \longrightarrow F \longrightarrow G}$$
* Durée totale : $5 + 6 + 7 + 3 + 2 = \mathbf{23\text{ jours}}$.
* *Remarque pour l'oral :* La branche $A \rightarrow B \rightarrow D \rightarrow F \rightarrow G$ dure $5 + 4 + 8 + 3 + 2 = 22$ jours. La tâche $D$ dispose d'un jour de flottement (marge totale = 1 jour).

#### Étape 5 : Représentation sur Diagramme de Gantt
```
Jours :  01  03  05  07  09  11  13  15  17  19  21  23
Tâche A  [█████]                                      (Critique)
Tâche B        [████]...                              (Marge de 1j)
Tâche C        [██████]                               (Critique)
Tâche D            [████████]...                      (Marge de 1j)
Tâche E                  [███████]                    (Critique)
Tâche F                          [███]                (Critique)
Tâche G                              [██]             (Critique)
Jalon                                   ◆             (Mise en Prod)
```

---

## Exercice 2 : Choix du Cycle de Vie Logiciel (Scénario d'Examen)

### Énoncé :
Un ministère lance un appel d'offres pour une plateforme de gestion des concours nationaux. Le cahier des charges impose une conformité réglementaire stricte, aucune dérive sur les fonctionnalités juridiques, mais une équipe d'inspection réclame une visibilité régulière.
Quel modèle de développement recommandez-vous et pourquoi ?

### Éléments de Réponse Attendus :
1. **Recommandation :** Un **modèle Hybride** ou un **Cycle en V avec itérations courtes (V-Model itératif)**.
2. **Justification :**
   * La rigueur réglementaire et contractuelle nécessite la traçabilité descendante et ascendante garantie par le cycle en V (tests d'acceptation alignés sur les exigences légales).
   * L'incorporation de revues régulières et de prototypes répond aux impératifs d'adaptation et de validation continue demandés par le comité de suivi.
"""

GPI_ASTUCES = r"""# Astuces d'Examen, Pièges Fréquents et Questions Corrigées

Retrouvez ici les points sensibles qui font la différence lors des épreuves de Gestion de Projets Informatiques et Systèmes d'Information.

---

## 1. Top 8 des Pièges d'Examen en GPI

| N° | Piège Fréquent | Règle d'Or à Retenir |
| :---: | :--- | :--- |
| **1** | **Confondre Chemin Critique et nombre de tâches** | Le chemin critique est la suite de tâches de **durée totale MAXIMALE**, pas celle qui compte le plus grand nombre de tâches ! |
| **2** | **Marge Totale ($MT$) vs Marge Libre ($ML$)** | $MT$ = retard toléré sans retarder le **projet**. $ML$ = retard toléré sans retarder la **tâche suivante au plus tôt**. $ML \le MT$ toujours. |
| **3** | **Durée d'un Jalon (*Milestone*)** | Un jalon dans un diagramme de Gantt ou PERT a **toujours une durée égale à 0** ! Il marque un état ou une validation. |
| **4** | **Le Cycle en V n'est PAS Agile** | Le cycle en V est un modèle prédictif / séquentiel structuré avec validation. Il ne permet pas de refondre le périmètre à chaque sprint. |
| **5** | **Rôle du Scrum Master** | Le Scrum Master n'est **ni le chef hiérarchique**, ni le gestionnaire de budget, ni le Product Owner. C'est un **coach facilitateur** qui supprime les blocages. |
| **6** | **WBS vs Gantt** | Le WBS ne comporte **aucune date ni calendrier** ! Il découpe le périmètre en livrables. C'est le diagramme de Gantt qui gère le temps et les dates. |
| **7** | **Formule de la durée estimée PERT** | $T_e = \frac{O + 4M + P}{6}$ (Moyenne pondérée : le mode le plus probable a un poids de 4). |
| **8** | **Loi de Brooks** | « Ajouter des développeurs à un projet en retard ne fait que le retarder davantage » (à cause de l'explosion des coûts de communication). |

---

## 2. Tableau Comparatif des Rôles Clés

| Rôle | Responsabilité Principale | Outils Favoris |
| :--- | :--- | :--- |
| **Chef de Projet (PMP)** | Respect des délais, des coûts et du contrat global | Gantt, PERT, WBS, Matrice des risques |
| **Product Owner (PO)** | Définit le **QUOI** : priorisation de la valeur métier | Product Backlog, User Stories |
| **Scrum Master (SM)** | Définit le **COMMENT** : garant du cadre de travail | Rituels Scrum, Burndown Chart |
| **Équipe de Dév** | Réalisation technique et qualité du code | Git, CI/CD, Tests automatisés |

---

## 3. Questions Réelles de Concours Décortiquées

### Question 1 (Concours Administrateurs & Ingénieurs d'État)
**Énoncé :** Dans un réseau PERT, si une tâche a une marge totale de 3 jours et une marge libre de 0 jour :
* A. Tout retard sur cette tâche retardera le projet de 3 jours.
* **B. Un retard d'un jour sur cette tâche reportera le démarrage au plus tôt de la tâche suivante, mais ne retardera pas la fin du projet.** *(Bonne réponse)*
* C. Cette tâche fait partie du chemin critique.
* D. La tâche ne peut subir aucun retard.
> **Explication du jury :** Comme la marge totale est de 3 jours (> 0), la tâche n'est pas critique et un retard de 1 jour n'impacte pas l'échéance finale du projet. Cependant, sa marge libre étant de 0, tout retard consomme immédiatement la souplesse de la tâche successeur et décale son début au plus tôt.

---

### Question 2 (Concours CRMEF Enseignement Secondaire)
**Énoncé :** Quel est l'outil de gestion de projet qui permet d'afficher visuellement l'avancement temporel réel par rapport aux prévisions calendaires ?
* A. L'organigramme des tâches (WBS)
* B. La matrice RACI
* **C. Le diagramme de Gantt** *(Bonne réponse)*
* D. Le diagramme d'Ishikawa
> **Explication du jury :** Seul le diagramme de Gantt positionne les tâches sur une échelle calendaire réelle (jours/semaines) et permet de superposer l'état d'avancement réel par rapport aux barres planifiées. Le WBS décompose sans calendrier, et Ishikawa est un outil d'analyse causale.

---

### Question 3 (Concours Informatique 2024)
**Énoncé :** Dans la méthode Scrum, qui a le pouvoir d'annuler un Sprint en cours ?
* A. Le Scrum Master
* B. L'Équipe de Développement
* **C. Le Product Owner** *(Bonne réponse)*
* D. Le Directeur des Systèmes d'Information (DSI)
> **Explication du jury :** Selon le Guide Scrum officiel, seul le **Product Owner** dispose de l'autorité pour annuler un Sprint si l'objectif du Sprint devient obsolète suite à un changement stratégique majeur.
"""

def enrich_course_gpi(apps, schema_editor):
    Course = apps.get_model('syllabus', 'Course')
    
    # Target Course pk 3 (GPI)
    Course.objects.filter(pk=3).update(
        content=GPI_CONTENT,
        content_fr=GPI_CONTENT,
        examples=GPI_EXAMPLES,
        examples_fr=GPI_EXAMPLES,
        astuces=GPI_ASTUCES,
        astuces_fr=GPI_ASTUCES
    )

def reverse_enrich_gpi(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_enrich_uml_course'),
    ]

    operations = [
        migrations.RunPython(enrich_course_gpi, reverse_code=reverse_enrich_gpi),
    ]
