# Generated by Django on 2026-10-08

from django.db import migrations

LINUX_CONTENT = r"""# Commandes d'Administration et Scripts Shell Linux/Unix

Bienvenue dans ce cours complet consacré aux **Commandes d'Administration Système et à la Programmation Shell sous Linux/Unix**. Conçu spécifiquement pour les candidats préparant les concours d'ingénieurs, d'administrateurs et d'enseignement informatique, ce guide détaille l'ensemble des commandes indispensables, leurs nuances d'utilisation, ainsi que les pièges classiques posés aux examens.

---

## 1. Principes Fondamentaux et Arborescence Linux (FHS)

### A. La Philosophie UNIX
Le système d'exploitation Linux/Unix repose sur quatre grands principes d'ingénierie logicielle :
1. **« Tout est fichier »** : Les fichiers ordinaires, les répertoires, les périphériques matériels (`/dev`), les processus en cours d'exécution (`/proc`) et les connexions réseau sont manipulés via l'API des fichiers.
2. **Programmes modulaires spécialisés** : Chaque commande effectue **une seule tâche** et l'effectue parfaitement (ex : `grep` recherche, `sort` trie, `wc` compte).
3. **Chaînage des commandes** : La sortie standard d'un programme peut devenir directement l'entrée d'un autre via le mécanisme des **tubes (*pipes*)**.
4. **Interface textuelle universelle** : Les flux de communication entre programmes sont au format texte brut (*plain text*).

### B. L'Arborescence des Fichiers (Filesystem Hierarchy Standard - FHS)
Contrairement aux systèmes Windows organisés en lecteurs (`C:\`, `D:\`), Linux utilise une **racine unique notée `/`** sous laquelle viennent se greffer tous les disques et partitions.

![Arborescence Standard de Linux](/images/linux_tree.png)

| Répertoire | Rôle & Contenu | Remarques pour l'Examen |
| :--- | :--- | :--- |
| **`/`** | **Racine (*root*)** de tout le système de fichiers. | Point de départ de tous les chemins absolus. |
| **`/bin`** | Exécutables et commandes binaires essentiels pour tous les utilisateurs (`ls`, `cp`, `cat`, `bash`). | Nécessaire au démarrage du système. |
| **`/sbin`** | Commandes d'administration système réservées au super-utilisateur `root` (`fdisk`, `reboot`, `iptables`). | *System Binaries*. |
| **`/etc`** | **Fichiers de configuration** système (`/etc/passwd`, `/etc/shadow`, `/etc/fstab`, `/etc/hosts`). | Que du texte, aucun fichier binaire. |
| **`/home`** | Répertoires personnels des utilisateurs ordinaires (`/home/etudiant`). | Abrégé par le tilde `~`. |
| **`/root`** | Répertoire personnel du super-utilisateur (distinct de `/home`). | Ne pas confondre avec la racine `/`. |
| **`/var`** | Données variables (`/var/log` pour les journaux, `/var/mail`, `/var/www` pour le web). | Taille dynamique grandissante. |
| **`/tmp`** | Fichiers temporaires accessibles en écriture à tous. | Souvent vidé au redémarrage. |
| **`/dev`** | Fichiers spéciaux représentant les **périphériques matériels** (`/dev/sda` pour le disque, `/dev/null` pour le trou noir). | Interface matérielle. |
| **`/proc`** | **Système de fichiers virtuel** en mémoire RAM représentant le noyau et les processus actifs (`/proc/cpuinfo`, `/proc/meminfo`, `/proc/[PID]`). | Taille apparente = 0 octet sur disque. |

---

## 2. Navigation, Gestion des Fichiers et Nuances Indispensables

### A. Le Triptyque de Base : `pwd`, `cd` et `ls` (Comprendre leurs Différences)
L'interaction quotidienne avec le terminal repose sur trois commandes complémentaires :

| Commande | Nom complet | Action exacte | Impact sur le Shell |
| :--- | :--- | :--- | :--- |
| **`pwd`** | *Print Working Directory* | Affiche le chemin absolu du répertoire où l'utilisateur se trouve actuellement. | **Ne modifie rien** (lecture seule de l'état courant). |
| **`cd`** | *Change Directory* | Déplace l'utilisateur vers un autre répertoire. | **Modifie le contexte courant** du processus shell. |
| **`ls`** | *List* | Liste le contenu d'un répertoire (fichiers et sous-dossiers). | **Affiche le contenu** sans changer de répertoire. |

#### 1. Chemins Absolus vs Chemins Relatifs (Piège Fréquent)
* **Chemin Absolu :** Démarre **obligatoirement par la racine `/`**. Il identifie un fichier de manière universelle quel que soit le dossier courant.
  * Exemple : `cd /var/log/apache2`
* **Chemin Relatif :** Ne commence pas par `/`. Il est interprété **relativement au répertoire où l'on se trouve** :
  * `.` : Représente le répertoire courant.
  * `..` : Représente le répertoire parent (le dossier situé juste au-dessus).
  * `~` : Raccourci vers le répertoire personnel (*home directory*) de l'utilisateur connecté (`$HOME`).
  * `-` : Raccourci vers le répertoire de travail **précédent** (`cd -` équivaut à un retour arrière).

#### 2. Maîtriser la commande `ls` et ses Options Essentielles
* `ls` : Liste simple des noms de fichiers.
* `ls -l` : Format long et détaillé (affiche type, permissions, propriétaire, groupe, taille, date de modification).
* `ls -a` : Affiche **tous les fichiers, y compris les fichiers cachés** (fichiers commençant par un point `.`, comme `.bashrc`).
* `ls -lh` : Format long avec tailles lisibles par l'humain (*human-readable*, ex : `4.2M`, `12K`).
* `ls -lt` : Trie les fichiers par **date de modification décroissante** (les plus récents en premier).
* `ls -lS` : Trie les fichiers par **taille décroissante** (les plus volumineux en haut).
* `ls -R` : Affichage récursif de toute l'arborescence des sous-dossiers.

---

### B. Manipulation des Fichiers et Dossiers : `cp`, `mv`, `rm`, `touch`, `mkdir`

#### 1. Création
* **`touch fichier.txt`** : Crée un fichier vide s'il n'existe pas, ou met à jour sa date d'accès/modification (*timestamp*) s'il existe déjà.
* **`mkdir dossier`** : Crée un nouveau répertoire.
* **`mkdir -p a/b/c`** : L'option `-p` (*parents*) crée toute l'arborescence de sous-répertoires intermédiaires sans renvoyer d'erreur s'ils existent déjà.

#### 2. Copie vs Déplacement / Renommage (`cp` vs `mv`)
* **`cp source destination`** : Duplique le fichier vers une nouvelle cible.
  * Pour copier un dossier complet et son contenu, l'option **récursive `-r` ou `-R` est obligatoire** : `cp -r dossier_src dossier_dest`.
  * `cp -p` : Conserve les permissions d'origine, le propriétaire et les dates.
* **`mv source destination`** : Déplace un fichier ou un dossier, OU le renomme s'il reste dans le même répertoire.
  * ⚠️ *Différence système fondamentale :* `mv` sur un même système de fichiers ne déplace pas les données physiques sur le disque, il se contente de modifier le nom dans le répertoire et **conserve le même numéro d'Inode**. En revanche, `cp` crée un nouvel Inode et copie les blocs de données.

#### 3. Suppression (`rm` et `rmdir`)
* **`rmdir dossier`** : Supprime un répertoire **uniquement s'il est vide**.
* **`rm fichier`** : Supprime un fichier.
* **`rm -rf dossier`** : Supprime récursivement (`-r`) et sans demander de confirmation (`-f` pour *force*). **Attention : sous Linux, la suppression est irréversible (pas de corbeille en ligne de commande) !**

---

### C. Visualisation de Fichiers : `cat` vs `more` vs `less` vs `head` vs `tail`

| Commande | Rôle exact | Cas d'usage idéal |
| :--- | :--- | :--- |
| **`cat`** (*Concatenate*) | Affiche l'intégralité du contenu d'un coup dans le terminal. | Petits fichiers (ex : scripts, `/etc/resolv.conf`). |
| **`more`** | Pagination simple du texte (défilement vers le bas avec barre espace). | Ancienne pagination basique. |
| **`less`** | Pagination avancée interactive (permet de défiler vers le bas ET vers le haut avec les flèches, recherche avec `/mot`). | Gros fichiers texte et logs (n'a pas besoin de charger tout le fichier en mémoire). |
| **`head -n X`** | Affiche les **X premières lignes** d'un fichier (par défaut $X=10$). | Aperçu de l'en-tête d'un fichier CSV ou code. |
| **`tail -n X`** | Affiche les **X dernières lignes** d'un fichier (par défaut $X=10$). | Vérifier la fin d'un fichier. |
| **`tail -f fichier.log`** | Option **`-f` (*follow*)** : Surveille et affiche les nouvelles lignes ajoutées au fichier **en temps réel**. | Surveillance des logs serveur en direct. |

---

### D. Liens Physiques (*Hard Links*) vs Liens Symboliques (*Soft Links*) et Inodes

L'**Inode** (nœud d'index) est la structure de données interne à Linux qui stocke toutes les métadonnées d'un fichier (taille, permissions, propriétaire, horodatages, pointeurs vers les blocs disques), **à l'exception du nom du fichier**.

![Comparaison Liens Physiques vs Liens Symboliques](/images/linux_links_inodes.png)

| Caractéristique | Lien Physique (*Hard Link*) : `ln source cible` | Lien Symbolique (*Soft Link*) : `ln -s source cible` |
| :--- | :--- | :--- |
| **Numéro d'Inode** | **Identique** à celui de la source. | **Nouveau numéro d'Inode propre**. |
| **Nature de la cible** | C'est un nouveau nom pointant directement vers le même Inode. | C'est un fichier raccourci contenant textuellement le chemin vers la source. |
| **Si la source est supprimée** | Les données restent intactes ! Le compteur de liens diminue de 1. Les données sont libérées quand le compteur tombe à 0. | Le lien devient **rompu / orphelin** (*broken link*). |
| **Sur les répertoires** | **Interdit** (pour éviter les boucles cycliques). | **Autorisé**. |
| **Entre partitions différentes** | **Impossible** (les numéros d'inodes sont locaux à chaque partition). | **Possible**. |

---

## 3. Permissions, Droits d'Accès et Sécurité (`chmod`, `chown`, `umask`)

Chaque fichier et répertoire sous Linux est protégé par une matrice de droits d'accès rattachée à trois catégories d'utilisateurs :
* **`u` (*User / Propriétaire*)** : L'utilisateur possédant le fichier.
* **`g` (*Group / Groupe*)** : Les membres du groupe propriétaire.
* **`o` (*Others / Autres*)** : Tous les autres utilisateurs du système.

![Permissions et Droits d'Accès Linux](/images/linux_permissions.png)

### A. Décomposition de la Chaîne des Permissions
La commande `ls -l` produit une chaîne de 10 caractères (ex : `-rwxr-xr--`) :
1. **1er caractère (Type) :**
   * `-` : Fichier ordinaire.
   * `d` : Répertoire (*directory*).
   * `l` : Lien symbolique (*link*).
   * `c` / `b` : Périphérique caractère / bloc.
2. **Caractères 2 à 4 :** Droits du propriétaire (`rwx`).
3. **Caractères 5 à 7 :** Droits du groupe (`r-x`).
4. **Caractères 8 à 10 :** Droits des autres (`r--`).

### B. Signification des Droits (`r`, `w`, `x`) : Fichier vs Répertoire
⚠️ **Piège classique des concours :** Le droit `x` (exécution) n'a pas la même signification sur un fichier et sur un dossier !
* Sur un **Fichier** :
  * `r` (*read*) : Lire le contenu du fichier.
  * `w` (*write*) : Modifier ou écraser le contenu du fichier.
  * `x` (*execute*) : Exécuter le fichier comme un programme ou script binaire.
* Sur un **Répertoire** :
  * `r` : Lister le contenu du dossier avec `ls`.
  * `w` : **Créer, renommer ou supprimer des fichiers dans le dossier** (même si le fichier lui-même est protégé en écriture !).
  * `x` : **Traverser le dossier** avec `cd` ou accéder à ses fichiers enfants. Sans `x`, impossible d'entrer dans le dossier !

### C. Calcul Octal et Commande `chmod`
Chaque lettre correspond à une valeur binaire et décimale :
* **`r` = 4**
* **`w` = 2**
* **`x` = 1**
* **`-` = 0**

#### Exemples de conversion :
* `rwx` = $4 + 2 + 1 = 7$ (Accès total).
* `rw-` = $4 + 2 + 0 = 6$ (Lecture + Écriture).
* `r-x` = $4 + 0 + 1 = 5$ (Lecture + Exécution).
* `r--` = $4 + 0 + 0 = 4$ (Lecture seule).
* `---` = $0$ (Aucun droit).

#### Syntaxes de `chmod` :
* **Notation Octale :**
  * `chmod 755 script.sh` : Propriétaire = `rwx` (7), Groupe = `r-x` (5), Autres = `r-x` (5).
  * `chmod 644 document.txt` : Propriétaire = `rw-` (6), Groupe = `r--` (4), Autres = `r--` (4).
  * `chmod 700 secret/` : Accès exclusif au propriétaire.
* **Notation Symbolique :**
  * `chmod u+x script.sh` (Ajoute le droit d'exécution au propriétaire).
  * `chmod go-w fichier.txt` (Retire le droit d'écriture au groupe et aux autres).
  * `chmod a+r fichier.txt` (Ajoute le droit de lecture à tout le monde : `a` = *all*).

### D. Le Masque de Création : `umask` (Calcul Mathématique aux Concours)
La commande `umask` définit les permissions qui sont **automatiquement retirées** lors de la création d'un nouveau fichier ou dossier.

* **Droits théoriques maximum à la création :**
  * Pour un **Répertoire** : `777` (`rwxrwxrwx`).
  * Pour un **Fichier ordinaire** : `666` (`rw-rw-rw-`) *(car un fichier ne doit jamais être exécutable par défaut pour des raisons de sécurité)*.
* **Formule de calcul des permissions effectives :**
  $$\text{Droits Répertoire} = 777 - \text{umask}$$
  $$\text{Droits Fichier} = 666 - \text{umask}$$
* **Exemple avec `umask 022` :**
  * Dossier : $777 - 022 = \mathbf{755}$ (`rwxr-xr-x`).
  * Fichier : $666 - 022 = \mathbf{644}$ (`rw-r--r--`).
* **Exemple avec `umask 027` :**
  * Dossier : $777 - 027 = \mathbf{750}$ (`rwxr-x---`).
  * Fichier : $666 - 027 = \mathbf{640}$ (`rw-r-----`).

---

## 4. Flux Standards, Redirections et Tubes (*Pipes*)

Tout processus Linux lancé dans un terminal ouvre automatiquement **trois descripteurs de fichiers standards** :
* **0 : `stdin` (*Standard Input*)** : Entrée standard (par défaut le clavier).
* **1 : `stdout` (*Standard Output*)** : Sortie standard des résultats (par défaut l'écran).
* **2 : `stderr` (*Standard Error*)** : Sortie d'erreur (par défaut l'écran).

![Flux Standards et Redirections Linux](/images/linux_pipes.png)

### Tableau des Opérateurs de Redirection :
| Opérateur | Rôle exact | Exemple d'utilisation |
| :---: | :--- | :--- |
| **`>`** | Redirige `stdout` vers un fichier en **écrasant** son contenu préalable. | `ls -l > liste.txt` |
| **`>>`** | Redirige `stdout` vers un fichier en **ajoutant** à la fin (*append*). | `date >> historique.log` |
| **`<`** | Redirige `stdin` : le programme lit depuis un fichier au lieu du clavier. | `sort < noms.txt` |
| **`2>`** | Redirige **uniquement les erreurs** (`stderr`) vers un fichier. | `find / -name "*.conf" 2> erreurs.log` |
| **`2>&1`** | Redirige le flux d'erreur 2 vers le même endroit que le flux 1. | `commande > sortie.log 2>&1` |
| **`&>`** | Syntaxe moderne combinant `stdout` et `stderr` dans le même fichier. | `commande &> tout.log` |
| **`/dev/null`** | Le "trou noir" de Linux : supprime silencieusement les données envoyées. | `commande 2> /dev/null` (masque les erreurs). |

### Le Mécanisme du Tube (*Pipe* `|`)
Le tube `|` connecte directement la sortie standard du programme de gauche à l'entrée standard du programme de droite **sans passer par un fichier temporaire sur disque**.
* Exemple : `ps aux | grep nginx | wc -l`
  * 1. `ps aux` liste tous les processus.
  * 2. `grep nginx` filtre uniquement les lignes contenant "nginx".
  * 3. `wc -l` compte le nombre de lignes résultantes.

---

## 5. Recherche, Filtres Texte et Traitement de Données

* **`grep [options] motif fichier`** : Recherche de chaînes ou d'expressions régulières.
  * `-i` : Ignore la casse (majuscules/minuscules).
  * `-v` : Inverse la recherche (affiche les lignes qui **ne contiennent pas** le motif).
  * `-r` ou `-R` : Recherche récursive dans tous les sous-dossiers.
  * `-c` : Compte le nombre de lignes correspondantes.
  * `-n` : Affiche le numéro des lignes trouvées.
  * `-E` : Active les expressions régulières étendues (*regex* : `+`, `?`, `|`).
* **`find [chemin] [critères] [actions]`** : Recherche dans l'arborescence du système de fichiers.
  * `find /home -name "*.pdf"` : Cherche par nom.
  * `find /var/log -type f -size +10M` : Fichiers ordinaires de plus de 10 Mo.
  * `find /tmp -mtime +7 -exec rm {} \;` : Supprime les fichiers modifiés il y a plus de 7 jours.
* **`cut -d':' -f1 /etc/passwd`** : Découpe chaque ligne selon le délimiteur `:` et extrait le 1er champ (liste des utilisateurs).
* **`sort` et `uniq`** : Tri alphabétique/numérique (`sort -n`) et déduplication des lignes consécutives (`uniq -c` pour compter les occurrences).
* **`wc` (*Word Count*)** : `wc -l` (lignes), `wc -w` (mots), `wc -c` (octets).

---

## 6. Gestion des Processus, Ressources et Tâches Planifiées

* **`ps aux` ou `ps -ef`** : Affiche instantanément la liste complète des processus avec leur PID (*Process ID*), utilisateur, consommation CPU et mémoire.
* **`top` / `htop`** : Gestionnaire de tâches interactif en temps réel.
* **Signaux d'arrêt avec `kill`** :
  * `kill -15 PID` ou `kill -TERM PID` : Demande d'arrêt propre (laisse au processus le temps de sauvegarder).
  * `kill -9 PID` ou `kill -KILL PID` : **Arrêt forcé et immédiat** par le noyau (le processus ne peut pas intercepter ce signal).
* **Processus en arrière-plan** :
  * Ajouter `&` en fin de commande : lance la commande en tâche de fond (`./sauvegarde.sh &`).
  * `nohup commande &` : Permet au processus de continuer à tourner même après la fermeture de la session SSH.
* **Espace disque et mémoire** :
  * `df -h` (*Disk Free*) : Affiche l'espace libre et utilisé sur chaque partition en Mo/Go.
  * `du -sh dossier` (*Disk Usage*) : Calcule la taille totale occupée par un dossier spécifique.
  * `free -m` : Affiche l'utilisation de la mémoire RAM et du SWAP en mégaoctets.
* **Planification avec `crontab -e`** :
  Structure d'une ligne cron à 5 étoiles :
  ```
  ┌───────────── Minute (0 - 59)
  │ ┌─────────── Heure (0 - 23)
  │ │ ┌───────── Jour du mois (1 - 31)
  │ │ │ ┌─────── Mois (1 - 12)
  │ │ │ │ ┌───── Jour de la semaine (0 - 7, 0 et 7 = Dimanche)
  │ │ │ │ │
  * * * * *  commande_a_executer
  ```
  * Exemple : `0 2 * * * /backup.sh` (S'exécute tous les jours à 02h00 du matin).
  * Exemple : `*/15 * * * * check.sh` (S'exécute toutes les 15 minutes).

---

## 7. Programmation et Scripts Shell Bash

Un script Shell est un fichier texte contenant une suite de commandes exécutées par l'interpréteur de commandes.

### A. Le Shebang (`#!/bin/bash`)
La toute première ligne d'un script doit être le Shebang : `#!/bin/bash`. Elle indique au noyau quel interpréteur de commandes utiliser pour exécuter le script.
Pour rendre le script exécutable : `chmod +x mon_script.sh`, puis exécution avec `./mon_script.sh`.

### B. Variables et Variables Spéciales Prédéfinies
* Déclaration : `NOM="Rida"` *(Attention : aucun espace autour du signe `=` !)*.
* Utilisation : `$NOM` ou `${NOM}`.
* Différence entre guillemets doubles et simples :
  * `"Bonjour $NOM"` $\rightarrow$ Évalue la variable (*interpolation* : `Bonjour Rida`).
  * `'Bonjour $NOM'` $\rightarrow$ Texte brut littéral (`Bonjour $NOM`).

#### Les Variables Spéciales de Script (Posées à Chaque Concours) :
| Variable | Signification |
| :---: | :--- |
| **`$?`** | **Code de retour** de la dernière commande exécutée (0 = succès, différent de 0 = erreur). |
| **`$#`** | **Nombre d'arguments** passés au script. |
| **`$0`** | Nom du script lui-même. |
| **`$1`, `$2`, ...** | Valeur du 1er, 2ème argument positionnel. |
| **`$@`** | Liste de tous les arguments passés au script (séparés individuellement). |
| **`$$`** | PID (*Process ID*) du script en cours d'exécution. |

### C. Structures Conditionnelles et Tests
```bash
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <nom_fichier>"
    exit 1
elif [ -f "$1" ]; then
    echo "Le fichier $1 existe et est un fichier ordinaire."
elif [ -d "$1" ]; then
    echo "$1 est un répertoire."
else
    echo "$1 n'existe pas."
fi
```

#### Opérateurs de Comparaison :
* **Nombres entiers :** `-eq` (égal), `-ne` (différent), `-lt` (strictement inférieur), `-le` (inférieur ou égal), `-gt` (strictement supérieur), `-ge` (supérieur ou égal).
* **Chaînes :** `=` (égale), `!=` (différente), `-z` (vide), `-n` (non vide).
* **Fichiers :** `-f` (fichier ordinaire), `-d` (répertoire), `-e` (existe), `-r` (lisible), `-w` (inscriptible), `-x` (exécutable), `-s` (taille > 0).

### D. Boucles : `for` et `while`
```bash
# Boucle for sur les fichiers
for f in *.log; do
    echo "Traitement de : $f"
done

# Boucle while lisant un fichier ligne par ligne
while IFS= read -r ligne; do
    echo "Ligne : $ligne"
done < fichier.txt
```
"""

LINUX_EXAMPLES = r"""# Études de Cas Pratiques et Exercices Corrigés

Voici des exercices pratiques et scripts types fréquemment posés lors des épreuves d'administration système et d'informatique.

---

## Exercice 1 : Pipeline de Commandes et Traitement de Logs Serveur

### Énoncé :
Soit le fichier journal d'un serveur web Apache situé à `/var/log/apache2/access.log`. Chaque ligne commence par l'adresse IP du client, par exemple :
`192.168.1.50 - - [08/Oct/2026:10:00:00 +0000] "GET /index.html HTTP/1.1" 200 4520`

**Objectifs :**
1. Extraire les 10 adresses IP uniques ayant généré le plus grand nombre de requêtes, triées par ordre décroissant d'occurrences.
2. Compter le nombre total de requêtes ayant abouti à une erreur HTTP 404 (Page non trouvée).

---

### Solution Détaillée et Commentée :

#### 1. Trouver le Top 10 des adresses IP :
```bash
cut -d' ' -f1 /var/log/apache2/access.log | sort | uniq -c | sort -nr | head -n 10
```
* **Explication pas à pas :**
  1. `cut -d' ' -f1` : Découpe chaque ligne selon le délimiteur espace `' '` et extrait le 1er champ (l'adresse IP).
  2. `sort` : Trie les adresses IP par ordre alphabétique *(étape indispensable car `uniq` ne regroupe que les lignes consécutives)*.
  3. `uniq -c` : Déduplique les lignes identiques et préfixe chaque adresse IP par son nombre d'occurrences.
  4. `sort -nr` : Trie le résultat numériquement (`-n`) et dans l'ordre inverse / décroissant (`-r`).
  5. `head -n 10` : Affiche uniquement les 10 premières lignes (les 10 plus gros consommateurs).

#### 2. Compter les requêtes en erreur HTTP 404 :
```bash
grep " 404 " /var/log/apache2/access.log | wc -l
```
* `grep " 404 "` filtre les lignes contenant le code HTTP 404 entouré d'espaces, et `wc -l` compte le nombre total de ces lignes.

---

## Exercice 2 : Script de Sauvegarde Automatisée et Archivage Tar/Gzip

### Énoncé :
Écrire un script shell Bash nommé `sauvegarde.sh` qui :
1. Vérifie si le dossier source passé en premier paramètre existe.
2. Si aucun paramètre n'est fourni, affiche un message d'usage et quitte avec le code d'erreur 1.
3. Crée une archive compressée `.tar.gz` du dossier dans `/var/backups/` nommée avec la date du jour (format `YYYY-MM-DD`).
4. Vérifie si la commande d'archivage s'est bien déroulée en testant le code de retour `$?`.
5. Si succès, journalise l'opération avec la taille de l'archive dans `/var/log/sauvegardes.log`.

---

### Solution :
```bash
#!/bin/bash

# 1. Vérification du paramètre
if [ "$#" -ne 1 ]; then
    echo "Erreur: Syntaxe incorrecte."
    echo "Usage : $0 <repertoire_source>"
    exit 1
fi

SOURCE="$1"
DEST_DIR="/var/backups"
DATE_JOUR=$(date +%Y-%m-%d)
NOM_ARCHIVE="backup_$(basename "$SOURCE")_${DATE_JOUR}.tar.gz"

# 2. Vérification de l'existence du dossier source
if [ ! -d "$SOURCE" ]; then
    echo "Erreur: Le répertoire source '$SOURCE' n'existe pas."
    exit 2
fi

# 3. Création du dossier de destination si inexistant
mkdir -p "$DEST_DIR"

# 4. Création de l'archive compressée
tar -czf "${DEST_DIR}/${NOM_ARCHIVE}" "$SOURCE" 2>/dev/null

# 5. Vérification du code de retour $?
if [ "$?" -eq 0 ]; then
    TAILLE=$(du -h "${DEST_DIR}/${NOM_ARCHIVE}" | cut -f1)
    echo "[$(date)] SUCCES: Archive ${NOM_ARCHIVE} créée (${TAILLE})" >> /var/log/sauvegardes.log
    echo "Sauvegarde réussie : ${DEST_DIR}/${NOM_ARCHIVE} (${TAILLE})"
    exit 0
else
    echo "[$(date)] ECHEC: Erreur lors de la création de l'archive pour ${SOURCE}" >> /var/log/sauvegardes.log
    echo "Échec critique de la sauvegarde."
    exit 3
fi
```

---

## Exercice 3 : Résolution d'un Problème de Permissions et de Partage

### Énoncé :
Deux développeurs, `alice` et `bob`, appartiennent au même groupe `devs`.
On souhaite créer un répertoire `/projets/app` tel que :
* Tous les membres du groupe `devs` puissent créer, modifier et supprimer des fichiers dans le dossier.
* Les autres utilisateurs n'aient strictement aucun accès au dossier.
* Tout nouveau fichier créé dans ce dossier appartienne automatiquement au groupe `devs`.

### Solution :
```bash
# 1. Création du répertoire
sudo mkdir -p /projets/app

# 2. Attribution du propriétaire et du groupe
sudo chown root:devs /projets/app

# 3. Droits : 7 pour root, 7 pour devs, 0 pour autres + bit SGID (2)
sudo chmod 2770 /projets/app
```
* **Explication du bit SGID (`2xxx`) :** Le bit SGID (*Set Group ID*, valeur 2) positionné sur un **répertoire** force tous les nouveaux fichiers créés à l'intérieur à **hériter automatiquement du groupe du répertoire parent (`devs`)**, plutôt que du groupe primaire de l'utilisateur qui crée le fichier !
"""

LINUX_ASTUCES = r"""# Astuces d'Examen, Pièges Fréquents et Questions Corrigées

Retrouvez ici les points critiques, pièges récurrents et questions types d'examen en administration système Linux.

---

## 1. Le Top 10 des Pièges d'Examen sous Linux

| N° | Piège Fréquent | Règle d'Or à Retenir |
| :---: | :--- | :--- |
| **1** | **Espaces dans l'affectation de variable Bash** | `VAR = "val"` est une **erreur de syntaxe** ! Il ne doit y avoir **aucun espace** autour du signe `=` : `VAR="val"`. |
| **2** | **Différence `pwd` vs `cd` vs `ls`** | `pwd` affiche le dossier actuel sans rien changer. `cd` modifie le dossier courant. `ls` affiche le contenu sans déplacer l'utilisateur. |
| **3** | **Droit `x` sur un répertoire** | Sans le droit `x` (*traversée*), un utilisateur ne peut **ni faire `cd` dans le dossier, ni accéder aux fichiers qu'il contient**, même avec `r` ! |
| **4** | **Lien physique vs Lien symbolique** | Le lien physique partage le **même numéro d'Inode** et survit à la suppression de la source. Le lien symbolique a un Inode distinct et devient orphelin si la source est effacée. |
| **5** | **Sens de `>` vs `>>`** | `>` **écrase** le fichier cible (le vide avant d'écrire). `>>` **ajoute** à la fin du fichier sans rien effacer. |
| **6** | **Code de retour `$?`** | En Bash, **0 signifie SUCCÈS** et toute valeur différente de zéro (1 à 255) signifie une **ERREUR** (contrairement au C ou Java où 0 est faux et 1 est vrai). |
| **7** | **Calcul `umask`** | Pour un fichier, on soustrait de `666`. Pour un dossier, on soustrait de `777`. Un fichier créé n'est jamais exécutable par défaut. |
| **8** | **`sort` obligatoire avant `uniq`** | La commande `uniq` n'élimine que les lignes dupliquées **consécutives**. Pour un dédoublonnage global, il faut toujours faire `sort | uniq`. |
| **9** | **Signal `kill -9`** | `kill -9` envoie `SIGKILL` : il ne peut être **ni ignoré, ni intercepté** par le processus. Il termine le processus brutalement. |
| **10** | **Guillemets simples vs doubles** | `"$VAR"` évalue la variable. `'$VAR'` affiche littéralement la chaîne `$VAR`. |

---

## 2. Tableau Mémo-Technique des Commandes Essentielles

```
  CATÉGORIE         COMMANDE                 RÔLE ESSENTIEL
 ───────────       ──────────               ────────────────
  Navigation        pwd                      Affiche le répertoire courant
                    cd /chemin               Change de répertoire (cd -, cd ~, cd ..)
                    ls -lah                  Liste détaillée avec cachés et tailles lisibles
  Fichiers          touch f                  Crée fichier vide ou met à jour l'horodatage
                    mkdir -p a/b             Crée dossier et sous-dossiers parents
                    cp -r src dst            Copie récursive de dossier
                    mv src dst               Déplace ou renomme (conserve Inode)
                    rm -rf cible             Suppression récursive et forcée
  Visualisation     cat f                    Affiche tout d'un coup
                    less f                   Visualisation interactive avec défilement
                    head -n 5 / tail -n 5    Premières / Dernières lignes
                    tail -f f.log            Surveillance des logs en temps réel
  Recherche         grep -rin "mot" .        Recherche récursive, insensible à la casse
                    find / -name "*.sh"      Recherche de fichiers dans l'arborescence
  Droits            chmod 755 / 644          Modifie les permissions (r=4, w=2, x=1)
                    chown user:group f       Modifie le propriétaire et le groupe
  Processus         ps aux / top             Liste des processus actifs
                    kill -9 PID              Arrêt immédiat forcé
  Disque            df -h                    Espace libre par partition
                    du -sh dossier           Taille consommée par un répertoire
```

---

## 3. Cinq Questions Réelles de Concours Décortiquées

### Question 1
**Énoncé :** Quelle est la commande permettant d'afficher les lignes 15 à 25 d'un fichier texte `data.txt` ?
* A. `cat data.txt | head -n 15 | tail -n 25`
* **B. `head -n 25 data.txt | tail -n 11`** *(Bonne réponse)*
* C. `tail -n 25 data.txt | head -n 15`
* D. `sed -n '15,25' data.txt` *(sans l'option p)*
> **Explication du jury :** `head -n 25` extrait les 25 premières lignes du fichier. En envoyant ce résultat à `tail -n 11`, on récupère les 11 dernières lignes de ce sous-ensemble, ce qui correspond exactement aux lignes allant de 15 à 25 inclus ($25 - 15 + 1 = 11$). Alternative équivalente : `sed -n '15,25p' data.txt`.

---

### Question 2
**Énoncé :** Si le masque `umask` d'un utilisateur est configuré à `027`, quels seront les droits d'un nouveau fichier ordinaire et d'un nouveau répertoire créés par cet utilisateur ?
* A. Fichier : 640 ; Répertoire : 750
* **B. Fichier : 640 (`rw-r-----`) ; Répertoire : 750 (`rwxr-x---`)** *(Bonne réponse)*
* C. Fichier : 644 ; Répertoire : 755
* D. Fichier : 750 ; Répertoire : 640
> **Explication du jury :** Pour un répertoire, la base est `777` : $777 - 027 = 750$ (`rwxr-x---`). Pour un fichier, la base est `666` : $666 - 027 = 640$ (`rw-r-----`).

---

### Question 3
**Énoncé :** Que se passe-t-il lorsqu'on supprime le fichier source d'un lien physique (*hard link*) ?
* A. Le lien physique devient orphelin et inutilisable.
* **B. Les données restent accessibles via le lien physique car le fichier partage le même Inode.** *(Bonne réponse)*
* C. Le système d'exploitation renvoie une erreur de segmentation.
* D. Le lien physique est automatiquement converti en lien symbolique.
> **Explication du jury :** Un lien physique pointe directement vers l'Inode et les blocs de données. Supprimer le fichier source décrémente simplement le compteur de liens de l'Inode. Tant que ce compteur est supérieur à zéro (ici 1 grâce au second lien), les données demeurent intactes et accessibles sur le disque.

---

### Question 4
**Énoncé :** Dans un script Bash, que contient la variable `$?` immédiatement après l'exécution d'une commande réussie ?
* A. 1
* **B. 0** *(Bonne réponse)*
* C. Le PID du processus
* D. Le texte de la sortie standard
> **Explication du jury :** Par convention universelle Unix/Linux, la valeur de retour 0 signale le succès d'une opération (`EXIT_SUCCESS`). Toute valeur entre 1 et 255 signale une condition d'erreur.

---

### Question 5
**Énoncé :** Quelle commande permet de rediriger à la fois la sortie standard et la sortie d'erreur d'un script `traitement.sh` vers un fichier `journal.log` ?
* A. `./traitement.sh 1> journal.log 2> journal.log`
* **B. `./traitement.sh > journal.log 2>&1`** *(Bonne réponse)*
* C. `./traitement.sh 2> journal.log 1>&2`
* D. `./traitement.sh | journal.log`
> **Explication du jury :** `> journal.log` redirige d'abord la sortie standard (1) vers `journal.log`. Ensuite, `2>&1` indique au shell d'envoyer la sortie d'erreur (2) vers le même descripteur que la sortie standard. L'option A causerait des conflits d'écrasement concurrent entre les deux flux.
"""

def enrich_course_linux(apps, schema_editor):
    Course = apps.get_model('syllabus', 'Course')
    
    # Target Course pk 8 (Commandes Linux & Shell)
    Course.objects.filter(pk=8).update(
        content=LINUX_CONTENT,
        content_fr=LINUX_CONTENT,
        content_ar=None,
        examples=LINUX_EXAMPLES,
        examples_fr=LINUX_EXAMPLES,
        examples_ar=None,
        astuces=LINUX_ASTUCES,
        astuces_fr=LINUX_ASTUCES,
        astuces_ar=None
    )

def reverse_enrich_linux(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0010_enrich_gpi_project_management_course'),
    ]

    operations = [
        migrations.RunPython(enrich_course_linux, reverse_code=reverse_enrich_linux),
    ]
