# Generated by Django on 2026-10-08

from django.db import migrations

COURSE11_CONTENT = r"""# Jeux d'Instructions, Exécution en Pipeline et Architectures Modernes

Bienvenue dans ce cours approfondi consacré aux **Jeux d'Instructions**, au **Pipeline d'Exécution**, aux **Processeurs Superscalaires**, au **Renommage de Registres (*Register Renaming*)** et aux **Architectures Multicœurs**. Conçu pour répondre aux questions pointues posées aux concours d'ingénieurs, d'administrateurs et d'enseignement informatique, ce guide couvre les mécanismes internes du processeur moderne et ses optimisations matérielles.

---

## 1. Principes du Pipeline d'Instructions (Instruction Pipelining)

### A. Qu'est-ce que le Pipeline ?
Le **pipeline** (ou chaînage) est une technique matérielle d'optimisation inspirée du travail à la chaîne industriel. Il permet d'exécuter plusieurs instructions de manière concurrente en divisant le traitement de chaque instruction en une suite d'étapes (étages) séquentielles indépendantes cadencées par l'horloge.

![Exécution en Pipeline dans un Processeur RISC à 5 Étages](/images/pipeline_stages.png)

### B. Les 5 Étages Classiques du Pipeline RISC
1. **IF (*Instruction Fetch* - Chargement) :** Le processeur lit l'instruction pointée par le **Compteur Ordinal (PC / *Program Counter*)** depuis la mémoire d'instructions (ou cache L1-I) et la stocke dans le **Registre d'Instruction (RI / IR)**. Le PC est incrémenté.
2. **ID (*Instruction Decode / Register Read* - Décodage) :** L'Unité de Contrôle décode l'opcode de l'instruction et lit simultanément les opérandes sources dans le banc de registres.
3. **EX (*Execute / ALU Operation* - Exécution) :** L'**Unité Arithmétique et Logique (UAL / ALU)** effectue l'opération requise (addition, soustraction, décalage, calcul de l'adresse mémoire effective).
4. **MEM (*Memory Access* - Accès Mémoire) :** Accès à la mémoire de données (cache L1-D) uniquement pour les instructions de chargement (`LOAD` / `lw`) ou d'écriture (`STORE` / `sw`).
5. **WB (*Write Back* - Réécriture) :** Le résultat calculé par l'ALU ou chargé depuis la mémoire est réécrit dans le registre de destination du banc de registres.

### C. Métriques de Performance du Pipeline
* **Cycle par Instruction (CPI) :** Dans un pipeline idéal sans aléas, une nouvelle instruction est complétée à **chaque cycle d'horloge**, soit un $\mathbf{CPI = 1}$.
* **Accélération (*Speedup*) théorique :** Pour un pipeline à $k$ étages, le gain de vitesse maximal par rapport à une exécution séquentielle non pipelinée est de $k$ fois (avec un grand nombre d'instructions $N$) :
  $$\text{Speedup} = \frac{N \times k}{k + N - 1} \xrightarrow{N \to \infty} k$$

---

## 2. Les Aléas de Pipeline (*Pipeline Hazards*) et leurs Résolutions

Un aléa est une situation empêchant l'instruction suivante de s'exécuter au cycle d'horloge prévu, provoquant un gel (*stall*) ou l'insertion de « bulles » d'attente.

### A. Aléas Structurels (*Structural Hazards*)
* **Cause :** Conflit de ressources matérielles (deux étages ont besoin du même composant au même cycle).
* **Exemple :** L'étage IF (lecture instruction) et l'étage MEM (lecture donnée) veulent accéder simultanément à la mémoire centrale.
* **Solution matérielle :** Architecture de Harvard avec caches L1 séparés : un cache d'instructions (L1-I) et un cache de données (L1-D).

### B. Aléas de Contrôle (*Control Hazards / Branch Hazards*)
* **Cause :** Provient des instructions de saut conditionnel (`beq`, `bne`, `jmp`). Le processeur ne sait pas quelle instruction charger tant que la condition de saut n'est pas évaluée à l'étage EX ou MEM.
* **Pénalité de branchement (*Branch Penalty*) :** Perte de 2 à 3 cycles d'horloge si le pipeline doit être vidé (*flush*).
* **Solutions :**
  * **Prédiction statique :** Supposer que les boucles arrières sont toujours prises (*branch taken*).
  * **Prédiction dynamique :** Utilisation d'une table d'historique de branchements (**BHT - *Branch History Table*** ou *Branch Target Buffer - BTB*).
  * **Exécution spéculative :** Le processeur charge et exécute les instructions de la branche présumée avant même de connaître le résultat du test.

### C. Aléas de Données (*Data Hazards*) : Dépendances Vraies vs Fausses
Lorsqu'une instruction dépend du résultat d'une instruction précédente non encore achevée, on distingue trois types de dépendances :

| Type d'Aléa | Nom complet | Nature de la dépendance | Exemple d'instructions |
| :---: | :--- | :--- | :--- |
| **RAW** | **Read After Write** | **Vraie Dépendance de Données** | $I_1 : R_1 \leftarrow R_2 + R_3$ <br> $I_2 : R_4 \leftarrow \mathbf{R_1} - R_5$ |
| **WAR** | **Write After Read** | **Fausse Dépendance (Anti-dépendance)** | $I_1 : R_4 \leftarrow \mathbf{R_1} + R_2$ <br> $I_2 : \mathbf{R_1} \leftarrow R_5 \times R_6$ |
| **WAW** | **Write After Write** | **Fausse Dépendance (Dépendance de sortie)** | $I_1 : \mathbf{R_1} \leftarrow R_2 + R_3$ <br> $I_2 : \mathbf{R_1} \leftarrow R_4 - R_5$ |

#### Solutions pour les Aléas RAW :
1. **Court-circuit / Contournement (*Forwarding / Bypassing*) :** Le résultat produit à la sortie de l'ALU (étage EX) est directement envoyé via un bus matériel spécial à l'entrée de l'ALU de l'instruction suivante, sans attendre l'étage WB.
2. **Gel de pipeline (*Pipeline Stall*) :** Insertion d'une bulle (`NOP`) si l'aléa provient d'une instruction `LOAD` immédiate (*Load-Use Hazard*).

---

## 3. Processeurs Superscalaires et Renommage de Registres (*Register Renaming*)

Les processeurs modernes ne se contentent plus d'exécuter une seule instruction par cycle dans l'ordre strict du programme : ils sont **superscalaires** (plusieurs unités d'exécution en parallèle) et pratiquent l'**Exécution dans le Désordre (*Out-of-Order Execution - OoO*)**.

![Renommage de Registres dans un Processeur](/images/register_renaming.png)

### A. Le Rôle Fondamental du « Register Renaming » (Question Clé de Concours)
Dans les processeurs modernes, le **renommage de registres (*Register Renaming*)** a pour rôle exclusif de :
$$\mathbf{\text{Éliminer les conflits liés aux fausses dépendances (WAR et WAW)}}$$

#### Pourquoi les fausses dépendances existent-elles ?
Le jeu d'instructions (architecture logique) ne fournit qu'un nombre restreint de registres logiques dits architecturaux (ex : 16 registres en x86, 32 registres en ARM ou MIPS : $R_0, R_1, \dots, R_{31}$). 
Très souvent, le compilateur réutilise le même registre $R_1$ pour deux calculs totalement indépendants simplement par manque de registres disponibles. 
* Si le processeur voulait exécuter ces deux calculs en parallèle ou dans le désordre, $I_2$ risquerait d'écraser $R_1$ avant que $I_1$ ne l'ait lu (**aléa WAR**) ou dans le mauvais ordre (**aléa WAW**).

### B. Mécanisme Matériel du Renommage
1. **Registres Physiques ($P_0 \dots P_{127}$) :** Le processeur intègre physiquement un très grand nombre de registres réels (souvent 128 à 256 registres physiques).
2. **Table de Correspondance (RAT - *Register Alias Table*) :** Le processeur mappe dynamiquement chaque registre logique $R_x$ vers un registre physique libre $P_y$.
   * Exemple :
     * $I_1 : R_1 \leftarrow R_2 + R_3 \implies$ $R_1$ est renommé vers le registre physique **$P_3$**.
     * $I_2 : R_1 \leftarrow R_4 - R_5 \implies$ $R_1$ est renommé vers un NOUVEAU registre physique libre **$P_8$**.
3. **Résultat :** Les instructions $I_1$ et $I_2$ écrivent dans deux registres physiques distincts ($P_3$ et $P_8$). **Le conflit WAR et WAW a totalement disparu !** Les deux instructions peuvent désormais s'exécuter **simultanément et en parallèle** sans attendre.
4. **Validation dans l'ordre (ROB - *Reorder Buffer*) :** Bien que les calculs s'exécutent dans le désordre, un tampon de réordonnancement garantit que les résultats sont validés et rendus définitifs (*commit / retire*) strictement dans l'ordre du programme d'origine.

---

## 4. Architectures Multicœurs (*Multicore Processors*)

![Architecture d'un Processeur Multicœur](/images/multicore_processor.png)

### A. Définition du terme « Multicœur » (Question Clé de Concours)
Le terme **multicœur (*multicore*)** pour un processeur désigne :
$$\mathbf{\text{Un processeur qui intègre plusieurs unités de traitement indépendantes (cœurs / cores) sur une seule puce (die) de silicium.}}$$

### B. Organisation Interne d'un CPU Multicœur
Contrairement à un système multiprocesseur classique (où plusieurs puces distinctes sont enfichées sur la carte mère), un processeur multicœur regroupe sur le même circuit intégré :
* **Plusieurs cœurs indépendants (Core 1, Core 2, Core 3, Core 4...) :**
  * Chaque cœur possède sa propre **Unité de Contrôle (UC)**, son **Unité Arithmétique et Logique (ALU)**, son banc de registres et son propre pipeline.
  * Chaque cœur dispose de ses mémoires caches privées ultra-rapides : **Cache L1 privé** (séparé en L1-I et L1-D) et **Cache L2 privé**.
* **Ressources partagées :**
  * **Cache L3 partagé (*Last Level Cache*) :** Accessible par tous les cœurs pour échanger des données à très haut débit.
  * **Contrôleur de mémoire RAM intégré (IMC) :** Gère les bus mémoire vers les barrettes DDR4/DDR5.
  * **Bus d'interconnexion interne (Ring Bus / Mesh) :** Relie tous les cœurs et caches.

### C. Multicœur vs Hyper-Threading (SMT)
* **Multicœur physique :** Duplication réelle des circuits de calcul (ALU, décodeurs). Deux cœurs exécutent véritablement deux instructions simultanément au même cycle.
* **Hyper-Threading / SMT (*Simultaneous Multithreading*) :** Duplication uniquement de l'état architectural (registres, PC), mais les unités d'exécution (ALU) restent partagées au sein d'un même cœur.

---

## 5. Jeux d'Instructions (ISA) et Modes d'Adressage

Le jeu d'instructions (ISA - *Instruction Set Architecture*) définit l'ensemble des opérations de base qu'un processeur sait exécuter.

### A. Architectures RISC vs CISC
| Critère | RISC (*Reduced Instruction Set Computer*) | CISC (*Complex Instruction Set Computer*) |
| :--- | :--- | :--- |
| **Philosophie** | Instructions simples de taille fixe, exécutées en 1 cycle. | Instructions complexes de taille variable, puissantes. |
| **Accès Mémoire** | Architecture *Load/Store* stricte (seuls `LOAD` et `STORE` accèdent à la RAM). | Les opérations arithmétiques peuvent accéder directement à la RAM (`ADD [BX], AX`). |
| **Registres** | Très grand nombre de registres généraux (ex : 32 registres). | Nombre restreint de registres (ex : 8 ou 16 registres). |
| **Décodage** | Câblé (très rapide et simple). | Microprogrammé (séquenceur complexe). |
| **Exemples** | ARM, MIPS, RISC-V. | x86 (Intel / AMD). |

### B. Les Modes d'Adressage Indispensables
Le mode d'adressage définit la manière dont l'instruction spécifie l'emplacement de ses opérandes :
1. **Adressage Immédiat :** La valeur de l'opérande est directement incluse dans le code de l'instruction.
   * Exemple : `MOV AX, 15` (La constante 15 est codée dans l'instruction).
2. **Adressage Direct (ou Absolu) :** L'instruction contient directement l'adresse mémoire de l'opérande.
   * Exemple : `MOV AX, [2000H]` (Charge le contenu situé à l'adresse mémoire `2000H`).
3. **Adressage par Registre :** L'opérande est contenu dans un registre du processeur.
   * Exemple : `ADD AX, BX` (Opération ultra-rapide entre registres internes).
4. **Adressage Indirect par Registre :** Un registre contient l'adresse mémoire où se trouve la donnée (notion de pointeur).
   * Exemple : `MOV AX, [BX]` (L'opérande est à l'adresse pointée par `BX`).
5. **Adressage Indexé / Basé :** L'adresse effective est la somme d'un registre de base et d'un déplacement (*offset*).
   * Exemple : `MOV AX, [BX + 4]` ou `MOV AX, [BX + SI]`.
6. **Adressage Relatif au Compteur Ordinal (PC-Relative) :** Utilisé pour les sauts conditionnels (`JMP +20`). L'adresse cible est relative à la position de l'instruction courante.
"""

COURSE11_EXAMPLES = r"""# Exercices Corrigés et Questions d'Examens Analysées

Retrouvez ici des cas concrets de calculs de cycles de pipeline et d'analyse des architectures modernes.

---

## Exercice 1 : Calcul de Cycles et Détection d'Aléas de Données

### Énoncé :
Soit un processeur RISC classique à 5 étages (IF, ID, EX, MEM, WB). On considère la séquence de code suivante :
```assembly
I1 : ADD R1, R2, R3      ; R1 = R2 + R3
I2 : SUB R4, R1, R5      ; R4 = R1 - R5
I3 : AND R6, R1, R7      ; R6 = R1 AND R7
```

**Questions :**
1. Quel type d'aléa de données existe entre $I_1$ et $I_2$, ainsi qu'entre $I_1$ et $I_3$ ?
2. En l'absence de mécanisme de contournement (*forwarding*), combien de cycles de gel (*stalls*) doivent être insérés entre $I_1$ et $I_2$ ?
3. Avec un mécanisme de contournement matériel (*forwarding* de EX vers EX), quel est l'impact sur l'exécution ?

---

### Solution Détaillée :

#### 1. Identification de l'aléa :
* $I_1$ écrit dans $R_1$ lors de son étage **WB (cycle 5)**.
* $I_2$ tente de lire $R_1$ lors de son étage **ID (cycle 3)**.
* Il s'agit d'un aléa **RAW (*Read After Write*)**, c'est-à-dire une **vraie dépendance de données**.
* La même dépendance RAW existe entre $I_1$ et $I_3$ (qui lit $R_1$ au cycle 4).

#### 2. Sans contournement (Forwarding désactivé) :
* Pour que $I_2$ lise la valeur correcte dans le banc de registres, la lecture (ID) ne peut se faire qu'au cycle 5 (si écriture en début de cycle et lecture en fin de cycle) ou cycle 6.
* Le processeur doit insérer **2 cycles de gel (*stalls* / bulles)** :
  * Cycle 1 : $I_1$ en IF
  * Cycle 2 : $I_1$ en ID, $I_2$ en IF
  * Cycle 3 : $I_1$ en EX, $I_2$ bloqué en ID (*Bulle 1*)
  * Cycle 4 : $I_1$ en MEM, $I_2$ bloqué en ID (*Bulle 2*)
  * Cycle 5 : $I_1$ en WB, $I_2$ débloqué en EX

#### 3. Avec contournement (Forwarding actif) :
* Le résultat de $R_1$ est calculé dès la fin de l'étage **EX** de $I_1$ (cycle 3).
* Le circuit de court-circuit renvoie directement ce résultat à l'entrée de l'ALU pour l'étage EX de $I_2$ au cycle 4.
* **Résultat : ZÉRO cycle de gel !** Le pipeline s'exécute à plein régime sans aucune bulle.

---

## Exercice 2 : Résolution des Dépendances par Renommage de Registres

### Énoncé :
Soit le bloc d'instructions suivant soumis à un processeur superscalaire à exécution dans le désordre :
```assembly
I1 : MUL R1, R2, R3      ; R1 = R2 * R3 (Prend 4 cycles)
I2 : ADD R4, R1, R5      ; R4 = R1 + R5
I3 : SUB R1, R6, R7      ; R1 = R6 - R7 (Prend 1 cycle)
I4 : XOR R8, R1, R9      ; R8 = R1 XOR R9
```

**Questions :**
1. Identifier les dépendances de données entre ces instructions.
2. Expliquer comment le **renommage de registres** permet à $I_3$ et $I_4$ de s'exécuter avant que $I_1$ et $I_2$ ne soient terminés.

---

### Solution Détaillée :

#### 1. Analyse des dépendances :
* Entre $I_1$ et $I_2$ : **RAW** sur $R_1$ (vraie dépendance : $I_2$ attend le résultat de la multiplication).
* Entre $I_2$ et $I_3$ : **WAR** sur $R_1$ (fausse dépendance : $I_3$ veut écrire dans $R_1$ alors que $I_2$ doit d'abord lire l'ancien $R_1$).
* Entre $I_1$ et $I_3$ : **WAW** sur $R_1$ (fausse dépendance de sortie : les deux instructions écrivent dans $R_1$).
* Entre $I_3$ et $I_4$ : **RAW** sur $R_1$ ($I_4$ attend le résultat de la soustraction).

#### 2. Rôle du renommage de registres (*Register Renaming*) :
Sans renommage, $I_3$ est contrainte d'attendre que $I_1$ et $I_2$ aient achevé leur exécution (4 cycles) pour éviter d'écraser $R_1$ prématurément.

**Avec renommage de registres physiques :**
* Le processeur associe $R_1$ de $I_1$ au registre physique **$P_{10}$** $\implies I_1 : P_{10} \leftarrow R_2 \times R_3$ et $I_2 : R_4 \leftarrow P_{10} + R_5$.
* Lorsque $I_3$ se présente, le décodeur alloue un **NOUVEAU registre physique libre $P_{20}$** pour stocker son résultat :
  $$I_3 : P_{20} \leftarrow R_6 - R_7 \quad \text{et} \quad I_4 : R_8 \leftarrow P_{20} \oplus R_9$$
* **Conséquence spectaculaire :** Les fausses dépendances WAR et WAW sur le nom « R1 » sont totalement brisées. $I_3$ et $I_4$ peuvent s'exécuter **immédiatement dans une autre unité de calcul**, sans attendre la fin des 4 cycles de la multiplication de $I_1$ !
"""

COURSE11_ASTUCES = r"""# Astuces d'Examen, Pièges Fréquents et Questions Corrigées

Retrouvez ici les définitions clés et questions réelles d'examens posées lors des concours d'ingénieurs et d'informatique.

---

## 1. Synthèse Express des Concepts Clés

| Concept | Définition Exacte pour le Concours | Mot-Clé à Retenir |
| :--- | :--- | :--- |
| **Register Renaming** | Technique matérielle permettant d'**éliminer les fausses dépendances (WAR et WAW)** en associant dynamiquement les registres logiques à un grand nombre de registres physiques. | **Évite conflits WAR/WAW** |
| **Processeur Multicœur** | Intègre **plusieurs unités de traitement indépendantes (cœurs / cores)** sur une seule puce physique de silicium (*die*). | **Plusieurs cœurs indépendants** |
| **ALU (UAL)** | Composant du processeur qui effectue les opérations arithmétiques (addition, soustraction) et logiques (ET, OU, décalages). | **Calcul arithmétique & logique** |
| **Forwarding (Bypass)** | Circuit matériel court-circuitant le banc de registres pour transmettre directement le résultat de l'ALU à l'instruction suivante. | **Résout aléas RAW sans stall** |
| **Architecture Harvard** | Sépare physiquement la mémoire d'instructions et la mémoire de données (utilisée dans les caches L1 pour éviter les aléas structurels). | **Bus/Caches séparés I et D** |
| **DRAM vs SRAM** | La **DRAM** stocke l'information dans des condensateurs qui fuient et **exige un rafraîchissement périodique**. La **SRAM** est à base de bascules (transistors), sans rafraîchissement, plus rapide et utilisée pour le cache. | **Condensateur = Rafraîchissement** |

---

## 2. Décryptage des Questions Réelles de Concours

### Question 1 (Concours 2025 - Q62)
**Énoncé :** Dans les processeurs, le rôle du « register renaming » est de :
* A. Réduire le nombre de registres physiques.
* B. Améliorer la virtualisation.
* **C. Éviter les conflits liés aux dépendances fausses (WAR et WAW).** *(Bonne réponse)*
* D. Protéger les registres contre les attaques logicielles.
> **Explication du jury :** Le renommage de registres (*register renaming*) est une optimisation matérielle des architectures superscalaires à exécution dans le désordre (*Out-of-Order*). En mappant les registres d'architecture (limités) sur un ensemble plus vaste de registres physiques, il brise les dépendances dites "de nom" (WAR et WAW), permettant à des instructions indépendantes de s'exécuter en parallèle.

---

### Question 2 (Concours 2025 - Q63)
**Énoncé :** Le terme "multicœur" pour un processeur désigne :
* A. Un processeur qui possède une seule mémoire cache.
* **B. Un processeur qui contient plusieurs unités de traitement indépendantes (cœurs).** *(Bonne réponse)*
* C. Un processeur capable de changer de fréquence automatiquement.
* D. Un processeur qui possède une mémoire vive intégrée.
> **Explication du jury :** Un processeur multicœur réunit sur une même puce de silicium plusieurs cœurs de calcul complets et autonomes, chacun capable d'exécuter son propre flux d'instructions simultanément.

---

### Question 3 (Concours 2025 - Q64)
**Énoncé :** Le composant du processeur qui exécute les opérations arithmétiques et logiques est :
* A. L'Unité de Contrôle
* B. Le Registre d'Instruction
* C. Le Bus de données
* **D. L'Unité Arithmétique et Logique (UAL / ALU).** *(Bonne réponse)*
> **Explication du jury :** L'UAL (Arithmetic Logic Unit) est le bloc fonctionnel chargé de réaliser les opérations élémentaires de calcul (additions, soustractions, comparaisons, opérations booléennes ET/OU/NON). L'Unité de Contrôle, quant à elle, décode et pilote le séquencement.

---

### Question 4 (Concours 2025 - Q60)
**Énoncé :** Le rafraîchissement de la mémoire DRAM est nécessaire parce que :
* **A. Les condensateurs qui stockent les charges électriques se déchargent au cours du temps.** *(Bonne réponse)*
* B. Les transistors chauffent excessivement.
* C. L'horloge du processeur est trop rapide.
* D. La tension électrique fluctue constamment.
> **Explication du jury :** Une cellule de mémoire DRAM (Dynamic RAM) est constituée d'un transistor et d'un minuscule condensateur. En raison des courants de fuite naturels, le condensateur perd sa charge en quelques millisecondes. Un circuit de rafraîchissement périodique doit relire et réécrire la charge pour conserver la donnée.

---

### Question 5 (Concours 2023 - Q58)
**Énoncé :** Un bus d'adresse sur 16 bits représente une capacité d'adressage maximale de :
* A. 16 Ko
* B. 32 Ko
* **C. 64 Ko** *(Bonne réponse)*
* D. 128 Ko
> **Explication du jury :** Avec un bus d'adresse de $n=16$ bits, le nombre de cases mémoire adressables individuellement est $2^{16} = 65\,536$ adresses. Chaque case contenant 1 octet (8 bits), la capacité maximale est de $65\,536\text{ octets} = \frac{65536}{1024}\text{ Ko} = \mathbf{64\text{ Ko}}$.
"""

def enrich_course_pipeline_multicore(apps, schema_editor):
    Course = apps.get_model('syllabus', 'Course')
    
    # Target Course pk 11 (Pipeline, Register Renaming, Multicore)
    Course.objects.filter(pk=11).update(
        content=COURSE11_CONTENT,
        content_fr=COURSE11_CONTENT,
        content_ar=None,
        examples=COURSE11_EXAMPLES,
        examples_fr=COURSE11_EXAMPLES,
        examples_ar=None,
        astuces=COURSE11_ASTUCES,
        astuces_fr=COURSE11_ASTUCES,
        astuces_ar=None
    )

def reverse_enrich_pipeline_multicore(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0011_enrich_linux_shell_course'),
    ]

    operations = [
        migrations.RunPython(enrich_course_pipeline_multicore, reverse_code=reverse_enrich_pipeline_multicore),
    ]
