# Generated by Django on 2026-10-09

from django.db import migrations

def enrich_course_excel(apps, schema_editor):
    Course = apps.get_model('syllabus', 'Course')
    
    # Extract enriched text from initial_data.json or embedded string
    import json, os
    json_path = os.path.join(os.path.dirname(__file__), '../../initial_data.json')
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    excel_item = next((x for x in data if x.get('model') == 'syllabus.course' and x.get('pk') == 16), None)
    if excel_item:
        f = excel_item['fields']
        Course.objects.filter(pk=16).update(
            content=f.get('content'),
            content_fr=f.get('content_fr'),
            content_ar=None,
            examples=f.get('examples'),
            examples_fr=f.get('examples_fr'),
            examples_ar=None,
            astuces=f.get('astuces'),
            astuces_fr=f.get('astuces_fr'),
            astuces_ar=None
        )

def reverse_enrich_excel(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0012_enrich_cpu_pipeline_multicore_courses'),
    ]

    operations = [
        migrations.RunPython(enrich_course_excel, reverse_code=reverse_enrich_excel),
    ]
