# Generated by Django on 2026-10-09

from django.db import migrations

def enrich_course_powerpoint(apps, schema_editor):
    Course = apps.get_model('syllabus', 'Course')
    
    import json, os
    json_path = os.path.join(os.path.dirname(__file__), '../../initial_data.json')
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    ppt_item = next((x for x in data if x.get('model') == 'syllabus.course' and x.get('pk') == 18), None)
    if ppt_item:
        f = ppt_item['fields']
        Course.objects.filter(pk=18).update(
            content=f.get('content'),
            content_fr=f.get('content_fr'),
            content_ar=None,
            examples=f.get('examples'),
            examples_fr=f.get('examples_fr'),
            examples_ar=None,
            astuces=f.get('astuces'),
            astuces_fr=f.get('astuces_fr'),
            astuces_ar=None
        )

def reverse_enrich_powerpoint(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0013_enrich_excel_data_analysis_course'),
    ]

    operations = [
        migrations.RunPython(enrich_course_powerpoint, reverse_code=reverse_enrich_powerpoint),
    ]
