# Generated by Django on 2026-10-09

from django.db import migrations

def enrich_course_word(apps, schema_editor):
    Course = apps.get_model('syllabus', 'Course')
    
    import json, os
    json_path = os.path.join(os.path.dirname(__file__), '../../initial_data.json')
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    word_item = next((x for x in data if x.get('model') == 'syllabus.course' and x.get('pk') == 15), None)
    if word_item:
        f = word_item['fields']
        Course.objects.filter(pk=15).update(
            content=f.get('content'),
            content_fr=f.get('content_fr'),
            content_ar=None,
            examples=f.get('examples'),
            examples_fr=f.get('examples_fr'),
            examples_ar=None,
            astuces=f.get('astuces'),
            astuces_fr=f.get('astuces_fr'),
            astuces_ar=None
        )

def reverse_enrich_word(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0015_enrich_access_database_course'),
    ]

    operations = [
        migrations.RunPython(enrich_course_word, reverse_code=reverse_enrich_word),
    ]
